const $=id=>document.getElementById(id);const canvas=$("blackholeCanvas"),ctx=canvas.getContext("2d");const state={mode:"github",running:false,tasks:[],llmTaskId:"",absorption:null};
const dimensionText={product_level:"项目水平",architecture_depth:"架构深度",test_gate_evidence:"测试门禁",api_contract_quality:"接口契约",operational_readiness:"运行就绪",evolution_readiness:"进化就绪",external_ingestion:"外部摄取",comparative_analysis_depth:"对比深度",absorption_tasking:"吸收任务",employee_execution_integration:"员工执行",feedback_loop_closure:"反馈闭环",product_operability:"产品可用性",safety_license_gate:"安全许可",branch_absorption_workflow:"分支吸收",retort_product_maturity:"Retort 成熟度",calibrated_overall:"校准总分"};
const statusText={tasks_generated:"已生成吸收任务",no_external_advantage_found:"未发现外部优势",blocked_by_branch_workflow:"分支流程阻断",branch_created:"已创建吸收分支",merged:"已合并",disabled:"未启用",converged:"已收敛",blocked:"已阻断",max_rounds:"达到轮次上限",awaiting_execution_evidence:"等待执行证据",internalized_by_self_evolution:"已由反问内化",closed_loop_verified:"闭环证据已验证",closed_loop_evidence_required_before_scores_can_pass:"缺少闭环证据，不能通过高分门槛",all_scores_strictly_above_threshold:"全部分数已超过阈值",max_rounds_reached_before_all_scores_passed:"达到轮次上限但仍有分数未通过"};
const taskText={"Absorb stronger implementation depth":"吸收更强实现深度","Absorb better user experience":"吸收更好的用户体验","Absorb better operational gates":"吸收更强运行门禁","Adopt deterministic review pipeline stages":"接入确定性审查流水线","Add external file grouping before deep comparison":"深度对比前增加外部文件分组","Add absorption quality benchmark counters":"增加吸收质量基准计数","Expose Retort absorption through plugin friendly commands":"提供适合插件调用的吸收命令"};
const ownerText={"fhd-core-maintainer":"核心维护","market-frontend-dev":"前端体验","deploy-release-officer":"发布运维","test-qa-runner":"测试门禁"};
const labelOf=v=>dimensionText[v]||statusText[v]||taskText[v]||String(v||"");
const titleOf=v=>{const text=String(v||"");const match=text.match(/^Raise (.+) above (\d+)$/);return match?`将${labelOf(match[1])}提升到 ${match[2]} 以上`:labelOf(text)};
function setMode(mode){state.mode=mode;$("sourceGithub").classList.toggle("active",mode==="github");$("sourceFolder").classList.toggle("active",mode==="folder");$("githubRow").classList.toggle("hidden",mode!=="github");$("folderRow").classList.toggle("hidden",mode!=="folder")}
function body(){const own=$("ownProjectFolder").value.trim();const out={own_project:own,project:own,branch_workflow:$("branchWorkflow").checked,merge_after:$("mergeAfter").checked,run_local_gates:$("runGates").checked,use_llm:$("useLlm").checked,employee_queue:`${own}/.retort/employee_queue.jsonl`,history_store:`${own}/.retort/retort_history.sqlite`};if(state.mode==="github")out.github_url=$("githubUrl").value.trim();else out.external_path=$("externalProjectFolder").value.trim();return out}
async function api(path,payload){const r=await fetch(path,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const j=await r.json();if(!r.ok)throw new Error(j.error||"request failed");return j}
const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const clamp=(v,min,max)=>Math.max(min,Math.min(max,v));
const ease=v=>v<.5?2*v*v:1-Math.pow(-2*v+2,2)/2;
function beginAbsorption(payload){const source=payload.github_url||payload.external_path||"";const volume=clamp((source.length+(payload.own_project||"").length*.35)/120,.35,1.65);state.absorption={started:performance.now(),phase:"approach",volume,absorb:.65,radius:0,source,startAngle:-.42,seed:Math.abs(Math.sin(source.length*17.31))*999}}
function updateAbsorption(result){if(!state.absorption)return;const tasks=(result.tasks||[]).length,delta=(result.score_deltas||[]).filter(d=>d.delta>0).length;state.absorption.absorb=clamp(.55+tasks*.08+delta*.04,.7,1.75)}
function finishAbsorption(){if(!state.absorption)return wait(0);state.absorption.phase="consume";state.absorption.finishStarted=performance.now();return wait(2400)}
function cancelAbsorption(){if(!state.absorption)return;state.absorption.phase="recover";state.absorption.finishStarted=performance.now()}
function scores(list){$("scoreGrid").innerHTML="";const pick=list.filter(s=>["product_level","retort_product_maturity","external_ingestion","comparative_analysis_depth","branch_absorption_workflow","calibrated_overall"].includes(s.dimension));const rows=pick.length?pick:list.slice(0,6);$("coreScore").textContent=rows[0]?Math.round(rows[0].value):"--";for(const s of rows){const row=document.createElement("div");row.className="row";row.innerHTML=`<span>${labelOf(s.dimension)}</span><b>${Math.round(s.value)}</b><div class="meter"><i style="--w:${s.value}%"></i></div>`;$("scoreGrid").appendChild(row)}}
function tasks(list){$("taskList").innerHTML="";for(const t of list){const el=document.createElement("div");el.className="task";el.innerHTML=`<b>${titleOf(t.title)}</b><div>${ownerText[t.owner_hint]||t.owner_hint} · ${t.priority}</div>`;$("taskList").appendChild(el)}}
function llm(review){if(!review||review.enabled===false){$("llmState").textContent="排比 LLM 未启用";return}const d=review.dispatch||review;if(d.task_id)state.llmTaskId=d.task_id;$("llmState").textContent=d.status==="accepted"?`已派发排比任务：${d.task_id||"等待任务 ID"}`:`已写入排比待发箱：${d.reason||d.status||"等待调度"}`}
async function assess(){state.running=true;$("statusText").textContent="评估中";try{const r=await api("/api/assess",{project:$("ownProjectFolder").value.trim(),run_local_gates:$("runGates").checked,use_llm:$("useLlm").checked});scores(r.scores);llm(r.llm_review);$("statusText").textContent="已评估"}catch(e){$("statusText").textContent="已阻断";$("branchState").textContent=`错误：${e.message}`}finally{state.running=false}}
async function absorb(){state.running=true;$("statusText").textContent="吸收中";const payload=body();beginAbsorption(payload);try{const r=await api("/api/absorb",payload);updateAbsorption(r);scores(r.own_assessment.scores);tasks(r.tasks||[]);llm(r.llm_review);$("branchState").textContent=labelOf(r.branch_workflow?.status)||"尚未运行分支流程";$("statusText").textContent=labelOf(r.status);await finishAbsorption()}catch(e){cancelAbsorption();$("statusText").textContent="已阻断";$("branchState").textContent=`错误：${e.message}`}finally{state.running=false}}
async function evolve(){state.running=true;$("statusText").textContent="反问中";try{const r=await api("/api/self-evolve",{project:$("ownProjectFolder").value.trim(),run_local_gates:$("runGates").checked,max_rounds:8,use_llm:$("useLlm").checked});scores(r.final_assessment.scores);tasks(r.tasks||[]);llm(r.final_assessment?.llm_review||r.llm_review);$("branchState").textContent=`${labelOf(r.status)}：${labelOf(r.stop_reason)}`;$("statusText").textContent="已反问"}catch(e){$("statusText").textContent="已阻断";$("branchState").textContent=`错误：${e.message}`}finally{state.running=false}}
async function llmReview(){state.running=true;$("statusText").textContent="排比评审中";try{const payload=body();const r=await api("/api/llm-review",{project:payload.project,mode:"manual",github_url:payload.github_url||"",external_path:payload.external_path||"",run_local_gates:payload.run_local_gates});llm(r);$("statusText").textContent="已请求排比评审"}catch(e){$("statusText").textContent="已阻断";$("llmState").textContent=`错误：${e.message}`}finally{state.running=false}}
async function llmStatus(){if(!state.llmTaskId){$("llmState").textContent="没有可同步的排比任务";return}state.running=true;$("statusText").textContent="同步排比中";try{const r=await api("/api/llm-review-status",{task_id:state.llmTaskId});const json=r.json_result?` · JSON ${r.json_result.level||"已返回"}`:"";$("llmState").textContent=`排比任务 ${r.status||"unknown"} · 子任务 ${r.subtasks?.map(s=>s.status).join("/")||"无"}${json}`;$("statusText").textContent="已同步排比"}catch(e){$("statusText").textContent="已阻断";$("llmState").textContent=`错误：${e.message}`}finally{state.running=false}}
function star(i,w,h,t,dpr){const seed=Math.sin(i*981.17)*43758.5453,x=(seed-Math.floor(seed))*w,y=((Math.sin(i*427.41)*43758.5453)%1+1)%1*h,tw=.35+.65*Math.sin(t*.7+i);ctx.beginPath();ctx.fillStyle=`rgba(190,220,255,${.12+.25*tw})`;ctx.arc(x,y,(.45+(i%3)*.25)*dpr,0,Math.PI*2);ctx.fill()}
function disk(cx,cy,w,h,t,dpr){const speed=state.running?1.75:.72;ctx.save();ctx.translate(cx,cy);ctx.rotate(-.22);ctx.globalCompositeOperation="lighter";for(let i=0;i<34;i++){const p=i/33,rx=w*(.205+p*.205),ry=h*(.035+p*.064),phase=t*speed+i*.18,alpha=.035+(1-p)*.1;ctx.beginPath();ctx.ellipse(0,0,rx,ry,0,phase,phase+Math.PI*.95);ctx.strokeStyle=`rgba(77,211,255,${alpha*.65})`;ctx.lineWidth=(1.2+p*3.2)*dpr;ctx.stroke();ctx.beginPath();ctx.ellipse(0,0,rx*.98,ry*1.02,0,phase+Math.PI*.92,phase+Math.PI*1.95);ctx.strokeStyle=`rgba(255,184,82,${alpha*1.45})`;ctx.lineWidth=(1.4+p*3.9)*dpr;ctx.stroke()}for(let i=0;i<130;i++){const p=(i%65)/65,a=i*.71+t*speed*(.65+(i%7)*.035),rx=w*(.18+p*.27),ry=h*(.031+p*.081),x=Math.cos(a)*rx,y=Math.sin(a)*ry,tail=12*dpr+p*24*dpr;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x-Math.sin(a)*tail,y+Math.cos(a)*tail*.22);ctx.strokeStyle=i%4?`rgba(255,207,118,${.2+p*.46})`:`rgba(94,218,255,${.18+p*.35})`;ctx.lineWidth=(.8+p*1.5)*dpr;ctx.stroke()}ctx.restore()}
function planet(cx,cy,r,t,dpr){const a=state.absorption;if(!a)return{boost:0};const now=performance.now(),base=r*(.075+.032*a.volume),approach=clamp((now-a.started)/4200,0,1),consume=a.finishStarted?clamp((now-a.finishStarted)/2200,0,1):0,p=ease(approach),c=ease(consume),angle=a.startAngle+p*2.65+t*.08,dist=r*(.5-p*.36),x=cx+Math.cos(angle)*dist*.72,y=cy+Math.sin(angle)*dist*.46,rad=base*(1-c)*(1-p*.32),boost=(p*.45+c*.75)*a.absorb;if(c>=1){state.absorption=null;return{boost:0}}ctx.save();ctx.globalCompositeOperation="lighter";ctx.beginPath();ctx.strokeStyle=`rgba(255,190,96,${.3*(1-c)})`;ctx.lineWidth=1.3*dpr;ctx.ellipse(cx,cy,dist*.72,dist*.46,-.22,0,Math.PI*2);ctx.stroke();for(let i=0;i<24;i++){const q=i/23,tx=x+(cx-x)*q,ty=y+(cy-y)*q;ctx.beginPath();ctx.fillStyle=`rgba(255,177,84,${(.1+q*.34)*(1-c)})`;ctx.arc(tx,ty,Math.max(.9*dpr,rad*.11*(1-q)),0,Math.PI*2);ctx.fill()}ctx.globalCompositeOperation="source-over";let g=ctx.createRadialGradient(x-rad*.35,y-rad*.45,rad*.1,x,y,rad);g.addColorStop(0,"#f7fbff");g.addColorStop(.2,"#67d4ff");g.addColorStop(.55,"#2e6f9d");g.addColorStop(1,"#07101c");ctx.shadowColor="rgba(103,212,255,.82)";ctx.shadowBlur=24*dpr;ctx.beginPath();ctx.fillStyle=g;ctx.arc(x,y,Math.max(0,rad),0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.globalCompositeOperation="lighter";ctx.beginPath();ctx.strokeStyle=`rgba(103,212,255,${.55*(1-c)})`;ctx.lineWidth=1.7*dpr;ctx.arc(x,y,rad*1.2,0,Math.PI*2);ctx.stroke();ctx.restore();return{boost}}
function draw(){const rect=canvas.getBoundingClientRect(),dpr=devicePixelRatio||1,w=Math.max(1,rect.width*dpr),h=Math.max(1,rect.height*dpr);if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}const cx=w*.52,cy=h*.49,t=performance.now()/1000,r=Math.min(w,h);ctx.clearRect(0,0,w,h);let bg=ctx.createRadialGradient(cx,cy,r*.05,cx,cy,r*.78);bg.addColorStop(0,"#020206");bg.addColorStop(.18,"#050812");bg.addColorStop(.55,"#09182a");bg.addColorStop(1,"#020306");ctx.fillStyle=bg;ctx.fillRect(0,0,w,h);for(let i=0;i<180;i++)star(i,w,h,t,dpr);const boost=state.absorption?clamp(((performance.now()-state.absorption.started)/4200*.45+(state.absorption.finishStarted?(performance.now()-state.absorption.finishStarted)/2200*.75:0))*state.absorption.absorb,0,1.45):0;ctx.save();ctx.globalCompositeOperation="lighter";let halo=ctx.createRadialGradient(cx,cy,r*(.13+boost*.016),cx,cy,r*(.58+boost*.07));halo.addColorStop(0,`rgba(94,218,255,${.16+boost*.1})`);halo.addColorStop(.35,`rgba(255,184,82,${.1+boost*.12})`);halo.addColorStop(1,"rgba(0,0,0,0)");ctx.fillStyle=halo;ctx.fillRect(0,0,w,h);ctx.restore();disk(cx,cy,w,h,t,dpr);planet(cx,cy,r,t,dpr);ctx.save();ctx.translate(cx,cy);ctx.globalCompositeOperation="source-over";ctx.shadowColor="rgba(0,0,0,.95)";ctx.shadowBlur=(34+boost*16)*dpr;ctx.beginPath();ctx.fillStyle="#000";ctx.arc(0,0,r*(.142+boost*.024),0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;let ring=ctx.createRadialGradient(0,0,r*(.126+boost*.018),0,0,r*(.174+boost*.035));ring.addColorStop(0,"rgba(0,0,0,0)");ring.addColorStop(.48,`rgba(255,211,122,${.9+boost*.08})`);ring.addColorStop(.63,`rgba(96,221,255,${.55+boost*.18})`);ring.addColorStop(1,"rgba(0,0,0,0)");ctx.beginPath();ctx.fillStyle=ring;ctx.arc(0,0,r*(.18+boost*.04),0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.fillStyle="#000";ctx.arc(0,0,r*(.128+boost*.022),0,Math.PI*2);ctx.fill();ctx.restore();ctx.save();ctx.globalCompositeOperation="lighter";for(let i=0;i<42;i++){const a=i*.63-t*(state.running?1.6:.7),rr=r*(.2+(i%11)*.018+boost*.018),x=cx+Math.cos(a)*rr*1.58,y=cy+Math.sin(a)*rr*.45;ctx.beginPath();ctx.strokeStyle=`rgba(105,224,255,${.06+(i%5)*.025+boost*.025})`;ctx.lineWidth=(.8+(i%4)*.35)*dpr;ctx.arc(x,y,r*(.003+(i%3)*.001),0,Math.PI*2);ctx.stroke()}ctx.restore();requestAnimationFrame(draw)}
$("sourceGithub").onclick=()=>setMode("github");$("sourceFolder").onclick=()=>setMode("folder");$("assessBtn").onclick=assess;$("absorbBtn").onclick=absorb;$("evolveBtn").onclick=evolve;$("llmReviewBtn").onclick=llmReview;$("llmStatusBtn").onclick=llmStatus;draw();
