"""Versioned, server-owned course catalog for real business practice."""

from __future__ import annotations

from typing import Any

COURSE_VERSION = 4


def _step(
    step_id: str,
    title: str,
    *,
    goal: str,
    instruction: str,
    success: str,
    why: str,
    hint: str,
    route_name: str,
    target_selector: str,
    verifier: str,
    action_checklist: tuple[str, ...] = (),
    principle: str = "",
) -> dict[str, Any]:
    return {
        "id": step_id,
        "title": title,
        "goal": goal,
        "instruction": instruction,
        "success_criteria": success,
        "why": why,
        "hint": hint,
        "route_name": route_name,
        "target_selector": target_selector,
        "verifier": verifier,
        "required": True,
        "action_checklist": list(action_checklist),
        "principle": principle,
    }


COURSES: tuple[dict[str, Any], ...] = (
    {
        "id": "task-workspace",
        "title": "智能对话与任务工作区",
        "summary": "先完成两种只读查询，再在独立任务工作区核验状态与证据。",
        "estimated_minutes": 10,
        "prerequisite_ids": [],
        "version": COURSE_VERSION,
        "steps": [
            _step(
                "submit-readonly-query",
                "提交只读业务查询",
                goal="让小C产生一项真实、可追踪的只读任务。",
                instruction="先点击“新对话”创建独立工作区，再查询当前客户列表；教学空间没有客户时，空结果也是正确结果。",
                success="教学空间内出现属于你的已完成只读任务。",
                why="任务工作区展示的是后端持久任务，不是临时聊天动画。",
                hint="必须先点“新对话”，再输入：查询当前客户列表。不要创建、修改或删除数据。",
                route_name="chat",
                target_selector="[data-tour='chat-input-area']",
                verifier="completed_readonly_task",
                action_checklist=(
                    "点击新对话，保留已有销售任务工作区",
                    "输入只读问题",
                    "发送并等待任务完成",
                ),
                principle="先说清要查什么，再核对任务证据；查询不应产生业务写入。",
            ),
            _step(
                "inspect-task-evidence",
                "查看任务结果证据",
                goal="认识任务状态、进度、运行次数、未读与结果证据。",
                instruction="打开刚才的任务工作区并查看结果证据，然后返回验证。",
                success="提交的任务 ID 属于你、已完成且存在执行记录。",
                why="业务结果必须可以从任务追到执行证据。",
                hint="点击顶部任务入口，打开刚完成的任务。",
                route_name="chat",
                target_selector="[data-tutorial-id='task-workspace-list']",
                verifier="task_evidence_viewed",
                action_checklist=("打开顶部任务入口", "选择刚完成的工作区", "展开结果证据"),
                principle="聊天回答是入口，持久任务、运行记录和结果证据才是可追踪事实。",
            ),
            _step(
                "transfer-readonly-query",
                "换一个问题独立完成",
                goal="不用照抄上一句，也能独立完成第二项只读任务。",
                instruction="先点击“新对话”创建独立工作区，再用你自己的说法查询当前产品列表，并查看结果证据。",
                success="教学空间内出现第二项不同的已完成只读任务，且结果已查看。",
                why="能把同一方法迁移到新问题，才说明你掌握了任务工作区。",
                hint="必须先点“新对话”；表达可以不同，但必须是产品列表查询，不能创建或修改产品。",
                route_name="chat",
                target_selector="[data-tour='chat-input-area']",
                verifier="second_readonly_task",
                action_checklist=(
                    "点击新对话，创建第二个独立工作区",
                    "自行组织产品列表查询语句",
                    "等待任务完成",
                    "打开并查看第二项结果证据",
                ),
                principle="可复用结构：查询 + 业务对象 + 范围或条件。",
            ),
        ],
    },
    {
        "id": "master-data",
        "title": "客户与产品建档",
        "summary": "亲手建立销售闭环所需的精确客户和产品主数据。",
        "estimated_minutes": 10,
        "prerequisite_ids": [],
        "version": COURSE_VERSION,
        "steps": [
            _step(
                "create-customer",
                "创建客户B",
                goal="在教学空间建立唯一客户。",
                instruction="进入客户管理，点击“新建客户”，填写精确名称“客户B”并创建。",
                success="客户B 恰好一条。",
                why="精确且唯一的客户主数据是后续自动执行可判定的前提。",
                hint="不要添加空格，也不要写成客户 B。",
                route_name="customers",
                target_selector="[data-tutorial-id='customer-create']",
                verifier="exact_customer",
                action_checklist=("点击新建客户", "客户名称填写客户B", "点击创建"),
                principle="主数据先保证名称精确且唯一，后续业务才能稳定引用。",
            ),
            _step(
                "create-product",
                "创建 A 产品",
                goal="建立可销售、可扣减库存的产品。",
                instruction="进入产品管理，点击“添加产品”，填写名称“A 产品”、价格 100、初始库存 100 并保存。",
                success="A 产品恰好一条，价格为 100，库存为 100。",
                why="销售闭环会以这些精确字段做后端核验。",
                hint="产品名中的空格必须保留；产品型号会自动生成，无需填写。",
                route_name="products",
                target_selector="[data-tutorial-id='product-create']",
                verifier="exact_product",
                action_checklist=(
                    "点击添加产品",
                    "名称填写 A 产品",
                    "产品型号保持空白，由系统自动生成",
                    "价格填写 100",
                    "初始库存填写 100",
                    "点击保存",
                ),
                principle="产品名称、价格和库存是销售执行的三个独立事实，缺一不可。",
            ),
        ],
    },
    {
        "id": "sales-to-cash",
        "title": "销售到收款完整闭环",
        "summary": "从自然语言销售指令走到审批、订单、库存、开票、收款和凭证。",
        "estimated_minutes": 15,
        "prerequisite_ids": ["master-data"],
        "version": COURSE_VERSION,
        "steps": [
            _step(
                "submit-sales-sentence",
                "提交并确认销售任务",
                goal="生成一项真实待审批的销售闭环任务。",
                instruction="发送精确句子：把 A 产品卖给客户B，10 个，单价 100，开票收款；随后确认任务。",
                success="教学空间中出现与该句子关联的待审批申请，且尚未产生销售业务行。",
                why="高风险写操作必须先停在审批边界。",
                hint="不要改写产品名、客户名、数量或单价。",
                route_name="chat",
                target_selector="[data-tour='chat-input-area']",
                verifier="sales_waiting_approval",
                action_checklist=(
                    "发送精确业务句子",
                    "检查系统解析的客户、产品、数量和单价",
                    "确认任务",
                ),
                principle="可复用结构：把{产品}卖给{客户}，{数量}{单位}，单价{价格}，开票收款。",
            ),
            _step(
                "review-sales-approval",
                "核对审批详情",
                goal="在批准前确认这份申请就是刚才的销售任务。",
                instruction="进入审批工作台，打开待审批申请详情；核对客户B、A 产品、数量 10、单价 100，暂时不要批准。",
                success="真实待审批详情已经在页面中打开，且销售订单仍未生成。",
                why="审批不是形式按钮；批准前必须理解即将发生的业务副作用。",
                hint="如果列表有多条，按申请编号和完整任务句子核对。",
                route_name="approval-workspace",
                target_selector="[data-tutorial-id='approval-detail']",
                verifier="sales_approval_reviewed",
                action_checklist=("打开待审批申请", "核对申请描述和业务字段", "保持待审批状态"),
                principle="先核对对象、数量、金额和影响，再决定是否批准。",
            ),
            _step(
                "approve-sales-request",
                "批准并核验销售闭环",
                goal="在审批工作台批准真实申请并验证完整业务结果。",
                instruction="在已核对的审批详情中点击“通过”，等待任务恢复完成。",
                success="一单一明细；库存 100→90；订单已开票且已收款；收款核销存在；凭证借贷平衡。",
                why="只有持久业务副作用全部一致，销售任务才算完成。",
                hint="如果列表中有多条申请，请按任务句子和申请单号核对。",
                route_name="approval-workspace",
                target_selector="[data-tutorial-id='approval-approve-action']",
                verifier="sales_closed_loop",
                action_checklist=("点击通过", "等待工作流恢复完成", "返回实训教练验证结果"),
                principle="批准只应恢复同一请求一次；业务结果必须完整且不可重复。",
            ),
        ],
    },
    {
        "id": "data-import",
        "title": "业务文件导入",
        "summary": "使用内置教学 Excel 完成映射、预览、确认写入和结果核验。",
        "estimated_minutes": 12,
        "prerequisite_ids": [],
        "version": COURSE_VERSION,
        "steps": [
            _step(
                "import-preview",
                "上传并核对预览",
                goal="理解上传、目标选择、字段映射和预览边界。",
                instruction="在数据对接中心选择内置教学 Excel，完成目标和字段映射并生成预览。",
                success="存在属于你的 preview_ready 教学导入任务和逐行预览。",
                why="预览先于写入，可在错误进入业务库前发现问题。",
                hint="先检查成功行、错误行和实体匹配结果，再确认。",
                route_name="business-docking",
                target_selector="[data-tutorial-id='etl-upload']",
                verifier="etl_preview",
                action_checklist=(
                    "下载内置教学 Excel",
                    "选择文件与写入目标",
                    "核对字段映射",
                    "查看成功行和错误行预览",
                ),
                principle="先预览、后写入；错误行必须在进入业务库前可见。",
            ),
            _step(
                "import-execute",
                "确认写入并查看结果",
                goal="执行经过核对的导入草稿。",
                instruction="确认写入，并打开导入记录查看成功行和错误行结果。",
                success="导入任务完成、成功行大于零、逐行结果和实体引用均已持久化。",
                why="导入任务、逐行证据和业务实体必须可以相互追踪。",
                hint="验证失败时先查看错误行，不要重复上传同一文件。",
                route_name="business-docking",
                target_selector="[data-tutorial-id='etl-confirm']",
                verifier="etl_completed",
                action_checklist=("确认预览无误", "点击写入数据库", "打开运行历史和回执"),
                principle="一次导入必须能从文件追到任务、逐行结果和最终实体。",
            ),
        ],
    },
    {
        "id": "evidence-trace",
        "title": "结果核验与业务追踪",
        "summary": "沿任务、审批和财务业务对象追踪同一教学闭环。",
        "estimated_minutes": 12,
        "prerequisite_ids": ["task-workspace", "sales-to-cash", "data-import"],
        "version": COURSE_VERSION,
        "steps": [
            _step(
                "trace-task",
                "查看任务证据",
                goal="从任务定位执行结果。",
                instruction="打开销售任务的结果证据。",
                success="任务证据与教学空间的销售闭环关联。",
                why="任务是跨业务对象的入口。",
                hint="记录任务 ID 后验证。",
                route_name="chat",
                target_selector="[data-tutorial-id='task-workspace-list']",
                verifier="trace_task",
                action_checklist=("打开任务入口", "找到销售任务", "查看结果证据和运行记录"),
            ),
            _step(
                "trace-approval",
                "查看审批详情",
                goal="从任务追到审批申请。",
                instruction="打开已批准的销售审批详情。",
                success="审批申请属于同一教学租户并已批准。",
                why="审批证据解释了写操作为何获准。",
                hint="按申请单号核对。",
                route_name="approval-workspace",
                target_selector="[data-tutorial-id='approval-detail']",
                verifier="trace_approval",
                action_checklist=("打开已通过申请", "核对申请编号和审批记录"),
            ),
            _step(
                "trace-order",
                "查看销售订单",
                goal="核对订单和明细。",
                instruction="打开订单列表，找到客户B的销售订单并核对金额 1000。",
                success="恰好一张订单、一条 A 产品明细，数量 10、单价 100。",
                why="订单是库存和财务结果共同引用的业务源头。",
                hint="按客户B和订单金额 1000 定位。",
                route_name="orders",
                target_selector="[data-tutorial-id='tutorial-order-proof']",
                verifier="trace_order",
                action_checklist=("找到客户B订单", "核对一条明细", "核对数量、单价和金额"),
            ),
            _step(
                "trace-inventory",
                "查看库存扣减",
                goal="从产品库存核对履约结果。",
                instruction="打开库存管理，在库存表中找到 A 产品。",
                success="A 产品库存从 100 扣减到 90。",
                why="库存变化必须与订单数量完全一致。",
                hint="搜索 A 产品，核对当前库存 90。",
                route_name="inventory",
                target_selector="[data-tutorial-id='tutorial-inventory-proof']",
                verifier="trace_inventory",
                action_checklist=("找到 A 产品", "核对库存数量 90"),
            ),
            _step(
                "trace-invoice",
                "查看发票状态",
                goal="核对订单已经开票。",
                instruction="打开财务分析中的“本次销售财务证据”，查看发票卡片。",
                success="发票状态为已开票，订单金额 1000。",
                why="发票把销售事实转化为应收事实。",
                hint="核对订单引用、金额 1000 和已开票状态。",
                route_name="kitten-finance",
                target_selector="[data-tutorial-id='tutorial-finance-invoice']",
                verifier="trace_invoice",
            ),
            _step(
                "trace-receipt",
                "查看收款核销",
                goal="核对收款已经分配到同一订单。",
                instruction="在“本次销售财务证据”中查看收款核销卡片。",
                success="存在一条金额 1000 的已收款核销。",
                why="收款只有分配到应收，订单才真正结清。",
                hint="核对核销数量 1、金额 1000、状态已收款。",
                route_name="kitten-finance",
                target_selector="[data-tutorial-id='tutorial-finance-receipt']",
                verifier="trace_receipt",
            ),
            _step(
                "trace-vouchers",
                "查看记账凭证",
                goal="核对开票与收款凭证的借贷平衡。",
                instruction="在“本次销售财务证据”中查看凭证卡片。",
                success="开票和收款凭证均存在，所有凭证借贷平衡。",
                why="凭证平衡是财务闭环的最后一道确定性校验。",
                hint="核对凭证总数、开票凭证、收款凭证和平衡数量。",
                route_name="kitten-finance",
                target_selector="[data-tutorial-id='tutorial-finance-vouchers']",
                verifier="trace_vouchers",
            ),
            _step(
                "trace-import",
                "查看导入记录",
                goal="核对文件、逐行结果和业务实体关联。",
                instruction="返回数据对接中心并打开已完成的导入记录。",
                success="导入记录属于同一教学代次，且包含成功行和可审计结果。",
                why="文件导入也必须拥有与在线操作同等级的结果证据。",
                hint="打开最近一次 completed 记录。",
                route_name="business-docking",
                target_selector="[data-tutorial-id='etl-history']",
                verifier="trace_import",
                action_checklist=(
                    "打开运行历史",
                    "找到教学文件记录",
                    "查看成功行、错误行和实体引用",
                ),
            ),
        ],
    },
)

COURSE_BY_ID = {str(course["id"]): course for course in COURSES}


def public_course(course: dict[str, Any]) -> dict[str, Any]:
    """Strip server-only verifier keys before returning the public DTO."""
    result = {key: value for key, value in course.items() if key != "steps"}
    result["steps"] = [
        {key: value for key, value in step.items() if key != "verifier"} for step in course["steps"]
    ]
    return result


__all__ = ["COURSE_BY_ID", "COURSES", "COURSE_VERSION", "public_course"]
