"""Beginner-oriented content for the versioned tutorial course catalog."""

from typing import Any

from .builders import COURSE_VERSION, _guide, _step

COURSES: tuple[dict[str, Any], ...] = (
    {
        "id": "task-workspace",
        "title": "用小C提问并查看结果",
        "summary": "提出两个不会改动数据的问题，学会在“工作区”里找到进度和结果。",
        "estimated_minutes": 10,
        "prerequisite_ids": [],
        "version": COURSE_VERSION,
        "steps": [
            _step(
                "submit-readonly-query",
                "问第一个问题",
                goal="让小C完成一次客户列表查询。",
                instruction="新建对话，输入“查询当前客户列表”，发送后等待完成。",
                success="出现一项已经完成的客户查询任务。",
                why="先用不会改动数据的问题熟悉小C，操作更安心。",
                hint="如果没有客户，显示空列表也算查询成功。",
                route_name="chat",
                target_selector="#messageInput",
                verifier="completed_readonly_task",
                location_label="小C助理页面底部的输入区",
                completion_cue="在“工作区”里看到刚才的客户查询显示“已完成”。",
                guide_actions=(
                    _guide("点击“新对话”。", "#newConversationBtn"),
                    _guide("点击输入框，输入下面这句话。", "#messageInput", "查询当前客户列表"),
                    _guide("点击发送按钮。", "#sendMessageBtn"),
                    _guide(
                        "等待刚才的任务显示“已完成”。", "[data-tutorial-id='task-workspace-list']"
                    ),
                ),
                principle="查询只读取信息，不会新增、修改或删除业务数据。",
            ),
            _step(
                "inspect-task-evidence",
                "打开刚才的结果",
                goal="找到刚才任务的状态、进度和结果。",
                instruction="打开顶部“工作区”，选择刚完成的客户查询，再查看结果证据。",
                success="刚才的任务已完成，而且结果证据已经打开。",
                why="以后任务多了，可以从工作区知道哪项完成、哪项仍在处理。",
                hint="找标题里包含“客户列表”的工作区。",
                route_name="chat",
                target_selector="[data-tutorial-id='task-workspace-list']",
                verifier="task_evidence_viewed",
                location_label="小C助理页面顶部的“工作区”",
                completion_cue="看到任务状态、运行次数，以及“结果证据”。",
                guide_actions=(
                    _guide("点击页面顶部的“工作区”。", "[aria-label='打开独立工作区列表']"),
                    _guide(
                        "在列表中打开刚才的客户查询。", "[data-tutorial-id='task-workspace-list']"
                    ),
                    _guide("找到并查看“结果证据”。", ".agent-task-evidence"),
                ),
                principle="聊天是入口，工作区保存任务进度和可核对的结果。",
            ),
            _step(
                "transfer-readonly-query",
                "再问一个产品问题",
                goal="独立完成第二次查询。",
                instruction="新建对话，查询当前产品列表，等待完成并打开结果。",
                success="第二项产品查询已经完成，结果也已经查看。",
                why="换一个对象也能完成，才说明你真正会用了。",
                hint="这一步仍然只是查询，不会创建产品。",
                route_name="chat",
                target_selector="#messageInput",
                verifier="second_readonly_task",
                location_label="小C助理页面底部的输入区",
                completion_cue="在“工作区”里看到第二项产品查询已完成，并能看到结果证据。",
                guide_actions=(
                    _guide("点击“新对话”。", "#newConversationBtn"),
                    _guide("在输入框输入下面这句话。", "#messageInput", "查询当前产品列表"),
                    _guide("点击发送按钮并等待完成。", "#sendMessageBtn"),
                    _guide(
                        "打开“工作区”，查看这项任务的结果证据。",
                        "[data-tutorial-id='task-workspace-list']",
                    ),
                ),
                principle="提问时说清楚“查询什么对象”即可复用这个方法。",
            ),
        ],
    },
    {
        "id": "master-data",
        "title": "新建客户和产品",
        "summary": "照着页面建立客户B和 A 产品，为下一门销售练习准备数据。",
        "estimated_minutes": 10,
        "prerequisite_ids": [],
        "version": COURSE_VERSION,
        "steps": [
            _step(
                "create-customer",
                "新建客户B",
                goal="创建一个名称准确的客户。",
                instruction="在“组织管理”中点击“新建客户”，填写客户B并创建。",
                success="列表中只有一条名称为客户B的客户。",
                why="名称准确，后面的销售任务才能找到正确客户。",
                hint="必须写成“客户B”，中间不要加空格。",
                route_name="customers",
                target_selector="[data-tutorial-id='customer-create']",
                verifier="exact_customer",
                location_label="左侧菜单“组织管理”",
                completion_cue="客户列表中出现“客户B”。",
                guide_actions=(
                    _guide("点击“+ 新建客户”。", "[data-tutorial-id='customer-create']"),
                    _guide(
                        "在“客户名称”中输入下面的名称。",
                        "[data-tutorial-id='customer-name']",
                        "客户B",
                    ),
                    _guide("点击“创建”。", "[data-tutorial-id='customer-save']"),
                ),
                principle="客户名称要准确且唯一，销售任务才不会选错对象。",
            ),
            _step(
                "create-product",
                "新建 A 产品",
                goal="创建一个有价格和库存的产品。",
                instruction="在产品页面添加 A 产品，填写型号、价格和初始库存后保存。",
                success="A 产品只有一条，价格是 100，库存是 100。",
                why="销售会按产品名称找到它，再按数量扣减库存。",
                hint="产品名称“A 产品”中间有一个空格。",
                route_name="products",
                target_selector="[data-tutorial-id='product-create']",
                verifier="exact_product",
                location_label="左侧菜单“产品管理”",
                completion_cue="产品列表中出现“A 产品”，价格 100，库存 100。",
                guide_actions=(
                    _guide("点击“+ 添加产品”。", "[data-tutorial-id='product-create']"),
                    _guide(
                        "在“产品型号”中输入下面的型号。",
                        "[data-tutorial-id='product-model']",
                        "A-001",
                    ),
                    _guide(
                        "在“产品名称”中输入下面的名称。",
                        "[data-tutorial-id='product-name']",
                        "A 产品",
                    ),
                    _guide("在“价格”中输入 100。", "[data-tutorial-id='product-price']", "100"),
                    _guide(
                        "在“初始库存”中输入 100。", "[data-tutorial-id='product-inventory']", "100"
                    ),
                    _guide("点击“保存”。", "[data-tutorial-id='product-save']"),
                ),
                principle="产品名称、价格和库存是三个不同信息，要分别核对。",
            ),
        ],
    },
    {
        "id": "sales-to-cash",
        "title": "完成一笔销售并收款",
        "summary": "让小C准备销售，亲自检查并批准，然后确认订单、库存、发票和收款。",
        "estimated_minutes": 15,
        "prerequisite_ids": ["master-data"],
        "version": COURSE_VERSION,
        "steps": [
            _step(
                "submit-sales-sentence",
                "告诉小C要卖什么",
                goal="准备一笔 1000 元的销售任务。",
                instruction="发送指定销售句子，检查识别结果后确认任务。",
                success="出现一份等待批准的申请，此时还没有生成销售订单。",
                why="会改动业务数据的任务，必须先由人检查。",
                hint="产品、客户、数量和单价必须与练习句子完全一致。",
                route_name="chat",
                target_selector="#messageInput",
                verifier="sales_waiting_approval",
                location_label="小C助理页面底部的输入区",
                completion_cue="看到任务正在等待审批，而且系统还没有创建订单。",
                guide_actions=(
                    _guide(
                        "在输入框粘贴下面这句完整的话。",
                        "#messageInput",
                        "把 A 产品卖给客户B，10 个，单价 100，开票收款",
                    ),
                    _guide("点击发送按钮。", "#sendMessageBtn"),
                    _guide("核对客户B、A 产品、10 个、单价 100。", "#taskPanel"),
                    _guide(
                        "确认无误后点击“确认任务”。",
                        "#taskPanel button[data-action='confirm-task']",
                    ),
                ),
                principle="销售指令要包含产品、客户、数量、单价和是否开票收款。",
            ),
            _step(
                "review-sales-approval",
                "批准前先核对",
                goal="确认待审批内容就是刚才那笔销售。",
                instruction="在审批工作台打开待审批项，核对四个关键值，先不要批准。",
                success="审批详情已经打开，客户、产品、数量和单价都正确。",
                why="批准后会真正生成业务记录，所以必须先核对。",
                hint="如果有多条申请，找包含完整销售句子的那一条。",
                route_name="approval-workspace",
                target_selector="[data-tutorial-id='approval-detail']",
                verifier="sales_approval_reviewed",
                location_label="左侧菜单“审批工作台”",
                completion_cue="审批详情中能看到客户B、A 产品、10 个和单价 100。",
                guide_actions=(
                    _guide(
                        "在“待我审批”中打开刚才的销售申请。",
                        "[data-tutorial-id='approval-pending-list']",
                    ),
                    _guide("核对客户B和 A 产品。", "[data-tutorial-id='approval-detail']"),
                    _guide(
                        "再核对数量 10、单价 100；这一步不要点击“通过”。",
                        "[data-tutorial-id='approval-detail']",
                    ),
                ),
                principle="批准前固定核对对象、数量、单价和影响。",
            ),
            _step(
                "approve-sales-request",
                "批准并等待完成",
                goal="批准正确申请，让系统完成整笔销售。",
                instruction="点击“通过”，等待任务完成，然后回来检查结果。",
                success="一张订单、一条明细；库存变为 90；发票已收款；收款和记账结果齐全。",
                why="只有订单、库存和财务结果同时正确，这笔业务才算完成。",
                hint="只批准一次；按钮变为已处理后不要重复操作。",
                route_name="approval-workspace",
                target_selector="[data-tutorial-id='approval-approve-action']",
                verifier="sales_closed_loop",
                location_label="已打开的“审批详情”",
                completion_cue="申请显示已通过，任务恢复并完成。",
                guide_actions=(
                    _guide(
                        "点击审批详情里的“通过”。", "[data-tutorial-id='approval-approve-action']"
                    ),
                    _guide(
                        "等待申请显示已通过、任务显示已完成。",
                        "[data-tutorial-id='approval-detail']",
                    ),
                ),
                principle="同一申请只处理一次，系统必须避免重复生成订单。",
            ),
        ],
    },
    {
        "id": "data-import",
        "title": "导入一份业务 Excel",
        "summary": "使用内置练习文件，学会选择文件、核对字段、预览错误并确认写入。",
        "estimated_minutes": 12,
        "prerequisite_ids": [],
        "version": COURSE_VERSION,
        "steps": [
            _step(
                "import-preview",
                "上传并检查预览",
                goal="在写入前看懂文件会产生什么结果。",
                instruction="下载练习文件，上传后选择“客户及产品”，核对字段和预览。",
                success="页面出现可写入的正确行，同时清楚显示练习文件中的错误行。",
                why="先预览可以在数据写入前发现列对应错误或内容错误。",
                hint="练习文件故意放了一行错误数据，用来学习怎样识别错误。",
                route_name="business-docking",
                target_selector="[data-tutorial-id='etl-upload']",
                verifier="etl_preview",
                location_label="左侧菜单“数据对接中心”",
                completion_cue="进入“核对与写入”，同时看到正确行和错误行。",
                guide_actions=(
                    _guide("先点击教练下方的“下载内置教学 Excel”。", ".tutorial-coach__asset"),
                    _guide(
                        "点击“选择文件”，选择刚下载的 Excel。", "[data-tutorial-id='etl-upload']"
                    ),
                    _guide("把“目标”选为“客户及产品”。", "[data-tutorial-id='etl-target']"),
                    _guide("点击开始预览的按钮。", "[data-tutorial-id='etl-start-preview']"),
                    _guide(
                        "打开“字段映射”，核对源字段和目标字段。", "[data-tutorial-id='etl-mapping']"
                    ),
                    _guide(
                        "打开“核对与写入”，查看正确行和错误行。", "[data-tutorial-id='etl-preview']"
                    ),
                ),
                principle="导入时始终先核对，再写入。",
            ),
            _step(
                "import-execute",
                "确认写入并看回执",
                goal="只写入已经核对过的正确数据。",
                instruction="确认预览后点击“写入数据库”，再到运行历史查看回执。",
                success="导入已经完成，成功行、错误行和产生的记录都能查到。",
                why="回执能说明每一行成功还是失败，以及成功后写到了哪里。",
                hint="如果仍有不能写入的错误，按页面提示选择只写入正确行。",
                route_name="business-docking",
                target_selector="[data-tutorial-id='etl-confirm']",
                verifier="etl_completed",
                location_label="数据对接中心的“核对与写入”",
                completion_cue="运行历史显示本次导入“已完成”，并列出成功数和错误数。",
                guide_actions=(
                    _guide("最后核对一次预览结果。", "[data-tutorial-id='etl-preview']"),
                    _guide("点击“写入数据库”。", "[data-tutorial-id='etl-confirm']"),
                    _guide(
                        "打开“运行历史”，选择刚完成的记录。", "[data-tutorial-id='etl-history']"
                    ),
                    _guide("查看运行回执中的成功数、错误数和写入结果。", ".etl-receipt"),
                ),
                principle="文件、运行回执和最终记录应该能够互相对应。",
            ),
        ],
    },
    {
        "id": "evidence-trace",
        "title": "把一笔业务从头查到底",
        "summary": "依次打开任务、审批、订单、库存、发票、收款、凭证和导入记录。",
        "estimated_minutes": 12,
        "prerequisite_ids": ["task-workspace", "sales-to-cash", "data-import"],
        "version": COURSE_VERSION,
        "steps": [
            _step(
                "trace-task",
                "从销售任务开始",
                goal="找到刚才完成的销售任务。",
                instruction="打开“工作区”，找到销售任务并查看结果证据。",
                success="看到这项销售任务已经完成，并能看到结果证据。",
                why="任务是查找后续审批和业务结果的起点。",
                hint="找包含“客户B”和“A 产品”的任务。",
                route_name="chat",
                target_selector="[data-tutorial-id='task-workspace-list']",
                verifier="trace_task",
                location_label="小C助理页面顶部的“工作区”",
                completion_cue="销售任务显示“已完成”，结果证据已经展开。",
                guide_actions=(
                    _guide("点击顶部“工作区”。", "[aria-label='打开独立工作区列表']"),
                    _guide(
                        "打开包含客户B和 A 产品的销售任务。",
                        "[data-tutorial-id='task-workspace-list']",
                    ),
                    _guide("查看“结果证据”。", ".agent-task-evidence"),
                ),
            ),
            _step(
                "trace-approval",
                "查看是谁批准的",
                goal="找到这项销售对应的审批记录。",
                instruction="在审批工作台打开刚才已经通过的销售申请。",
                success="申请显示已通过，并且内容与销售任务一致。",
                why="审批记录说明这项写入为什么被允许执行。",
                hint="按申请编号和销售句子核对。",
                route_name="approval-workspace",
                target_selector="[data-tutorial-id='approval-detail']",
                verifier="trace_approval",
                location_label="左侧菜单“审批工作台”",
                completion_cue="审批详情显示“已通过”，并能看到审批记录。",
                guide_actions=(
                    _guide(
                        "打开“我发起的”中的已通过销售申请。",
                        "[data-tutorial-id='approval-initiated-list']",
                    ),
                    _guide(
                        "核对申请编号、内容和“已通过”状态。", "[data-tutorial-id='approval-detail']"
                    ),
                ),
            ),
            _step(
                "trace-order",
                "查看销售订单",
                goal="核对订单金额和产品明细。",
                instruction="在订单页面找到客户B的订单，核对 A 产品、数量和金额。",
                success="只有一张相关订单和一条明细，数量 10、单价 100、金额 1000。",
                why="订单是库存和财务结果共同引用的业务记录。",
                hint="按客户B和金额 1000 查找。",
                route_name="orders",
                target_selector="[data-tutorial-id='tutorial-order-proof']",
                verifier="trace_order",
                location_label="左侧菜单“订单管理”",
                completion_cue="看到客户B、A 产品、10 × 100 = 1000。",
                guide_actions=(
                    _guide(
                        "找到页面顶部的“本次教学销售结果”。",
                        "[data-tutorial-id='tutorial-order-proof']",
                    ),
                    _guide(
                        "核对客户B、A 产品、数量 10、单价 100、金额 1000。",
                        "[data-tutorial-id='tutorial-order-proof']",
                    ),
                ),
            ),
            _step(
                "trace-inventory",
                "查看库存为什么变少",
                goal="核对卖出 10 个后剩余库存。",
                instruction="在库存页面找到 A 产品，查看当前库存。",
                success="A 产品的库存从 100 变为 90。",
                why="库存减少量应该与订单销售数量完全相同。",
                hint="100 减去 10 应等于 90。",
                route_name="inventory",
                target_selector="[data-tutorial-id='tutorial-inventory-proof']",
                verifier="trace_inventory",
                location_label="左侧菜单“库存管理”",
                completion_cue="看到 A 产品当前库存为 90。",
                guide_actions=(
                    _guide(
                        "找到“本次教学库存结果”。", "[data-tutorial-id='tutorial-inventory-proof']"
                    ),
                    _guide(
                        "核对 A 产品的当前库存是 90。",
                        "[data-tutorial-id='tutorial-inventory-proof']",
                    ),
                ),
            ),
            _step(
                "trace-invoice",
                "查看发票",
                goal="确认订单已经开票。",
                instruction="在小猫财务分析中查看“本次销售财务证据”的发票卡片。",
                success="发票显示已开票，金额为 1000。",
                why="发票表示客户需要支付这笔销售款。",
                hint="核对状态和金额，不需要点击“开始分析”。",
                route_name="kitten-finance",
                target_selector="[data-tutorial-id='tutorial-finance-invoice']",
                verifier="trace_invoice",
                location_label="左侧菜单“小猫财务分析”",
                completion_cue="发票卡片显示“已开票”和金额 1000。",
                guide_actions=(
                    _guide("找到“本次销售财务证据”。", ".tutorial-finance-proof"),
                    _guide(
                        "查看“发票”卡片，核对状态和金额。",
                        "[data-tutorial-id='tutorial-finance-invoice']",
                    ),
                ),
            ),
            _step(
                "trace-receipt",
                "查看收款",
                goal="确认 1000 元已经收到并对应到这张订单。",
                instruction="查看同一区域里的“收款核销”卡片。",
                success="有一条 1000 元的收款，状态为已收款。",
                why="收到的钱与订单对应后，这笔订单才真正结清。",
                hint="核对 1 条、1000 元、已收款。",
                route_name="kitten-finance",
                target_selector="[data-tutorial-id='tutorial-finance-receipt']",
                verifier="trace_receipt",
                location_label="“本次销售财务证据”中的收款卡片",
                completion_cue="收款卡片显示 1 条、1000 元、已收款。",
                guide_actions=(
                    _guide("查看“收款核销”卡片。", "[data-tutorial-id='tutorial-finance-receipt']"),
                    _guide(
                        "核对收款数量、金额和状态。",
                        "[data-tutorial-id='tutorial-finance-receipt']",
                    ),
                ),
            ),
            _step(
                "trace-vouchers",
                "查看记账结果",
                goal="确认开票和收款都已经正确记账。",
                instruction="查看“记账凭证”卡片，核对开票、收款和借贷平衡。",
                success="开票凭证和收款凭证都存在，所有凭证借贷平衡。",
                why="借贷平衡说明这笔业务的财务记录完整。",
                hint="卡片中的平衡数应等于凭证总数。",
                route_name="kitten-finance",
                target_selector="[data-tutorial-id='tutorial-finance-vouchers']",
                verifier="trace_vouchers",
                location_label="“本次销售财务证据”中的记账凭证卡片",
                completion_cue="开票和收款凭证都存在，平衡数等于总数。",
                guide_actions=(
                    _guide(
                        "查看“记账凭证”卡片。", "[data-tutorial-id='tutorial-finance-vouchers']"
                    ),
                    _guide(
                        "核对开票凭证、收款凭证和借贷平衡数量。",
                        "[data-tutorial-id='tutorial-finance-vouchers']",
                    ),
                ),
            ),
            _step(
                "trace-import",
                "最后查看导入回执",
                goal="知道一份文件最终写入了哪些记录。",
                instruction="回到数据对接中心，打开刚才完成的运行记录和回执。",
                success="能看到成功行、错误行，以及成功行产生的记录。",
                why="以后导入出问题时，可以用回执定位到具体哪一行。",
                hint="选择刚才教学 Excel 对应的最新记录。",
                route_name="business-docking",
                target_selector="[data-tutorial-id='etl-history']",
                verifier="trace_import",
                location_label="数据对接中心的“运行历史”",
                completion_cue="回执中同时显示成功行、错误行和写入结果。",
                guide_actions=(
                    _guide("打开“运行历史”。", "[data-tutorial-id='etl-history']"),
                    _guide("选择刚才的教学 Excel 记录。", "[data-tutorial-id='etl-history']"),
                    _guide("查看运行回执中的成功行、错误行和写入结果。", ".etl-receipt"),
                ),
            ),
        ],
    },
)
