#!/usr/bin/env bash
# 将 modstore.service 对齐到与 remote_sync_extract.sh 相同的 MODstore_deploy 目录（drop-in 覆盖）。
# 需 root。用法（在服务器上）：
#   sudo MODSTORE_DEPLOY_DIR=/root/XCMAX/成都修茈科技有限公司/MODstore_deploy bash scripts/align_modstore_systemd_to_deploy.sh
# 同时安装后台任务单元 modstore-scheduler.service（参见 systemd/modstore-scheduler.service.example）：
#   sudo INSTALL_MODSTORE_SCHEDULER=1 MODSTORE_DEPLOY_DIR=/root/XCMAX/成都修茈科技有限公司/MODstore_deploy bash scripts/align_modstore_systemd_to_deploy.sh
#   或追加参数：sudo bash scripts/align_modstore_systemd_to_deploy.sh --with-scheduler
# 可选环境变量：
#   MODSTORE_UVICORN_PORT   默认 9999
#   MODSTORE_UVICORN_EXTRA  追加到 uvicorn 的额外参数（整段，注意引号），如 '--workers 2'
#   INSTALL_MODSTORE_SCHEDULER   设为 1 时写入并 enable modstore-scheduler.service
set -euo pipefail

if [ "$(id -u)" -ne 0 ]; then
  echo "[err] must run as root (systemd drop-in)" >&2
  exit 1
fi

INSTALL_SCHEDULER="${INSTALL_MODSTORE_SCHEDULER:-0}"
for _arg in "$@"; do
  case "$_arg" in
    --with-scheduler) INSTALL_SCHEDULER=1 ;;
  esac
done

DEPLOY_DIR="${MODSTORE_DEPLOY_DIR:-/root/XCMAX/成都修茈科技有限公司/MODstore_deploy}"
PORT="${MODSTORE_UVICORN_PORT:-9999}"
EXTRA="${MODSTORE_UVICORN_EXTRA:-}"

if [ ! -d "$DEPLOY_DIR" ]; then
  echo "[err] not a directory: $DEPLOY_DIR" >&2
  exit 1
fi
if [ ! -x "$DEPLOY_DIR/.venv/bin/python" ]; then
  echo "[err] missing venv: $DEPLOY_DIR/.venv/bin/python (先在该目录 pip install -e '.[web,knowledge]')" >&2
  exit 1
fi
if [ ! -f "$DEPLOY_DIR/modstore_server/app.py" ]; then
  echo "[err] not a MODstore_deploy tree: $DEPLOY_DIR" >&2
  exit 1
fi

DROP_DIR="/etc/systemd/system/modstore.service.d"
CONF="$DROP_DIR/99-modstore-deploy-dir.conf"

mkdir -p "$DROP_DIR"
if [ -f "$CONF" ]; then
  bak="/tmp/99-modstore-deploy-dir.conf.bak.$(date +%s)"
  cp -a "$CONF" "$bak"
  echo "[ok] backed up existing $CONF -> $bak"
fi

# systemd: ExecStart= 空行清除继承，下一行写入新命令
EXEC_CMD="$DEPLOY_DIR/.venv/bin/python -m uvicorn modstore_server.app:app --host 0.0.0.0 --port $PORT"
if [ -n "$EXTRA" ]; then
  EXEC_CMD="$EXEC_CMD $EXTRA"
fi

umask 022
cat >"$CONF" <<EOF
# Generated by align_modstore_systemd_to_deploy.sh — 与 sync 解压目录对齐
[Service]
WorkingDirectory=$DEPLOY_DIR
Environment=MODSTORE_RUN_BACKGROUND_JOBS=0
ExecStart=
ExecStart=$EXEC_CMD
EOF

echo "[ok] wrote $CONF"
systemctl daemon-reload
systemctl restart modstore
sleep 2
systemctl is-active modstore || true
code=$(curl -sS -o /dev/null -m 5 -w "%{http_code}" "http://127.0.0.1:${PORT}/api/health" 2>/dev/null || true)
code=${code:-000}
echo "[ok] curl http://127.0.0.1:${PORT}/api/health -> $code"
if [ "$code" != "200" ]; then
  echo "[warn] health not 200; check journal: journalctl -u modstore -n 80 --no-pager" >&2
  exit 1
fi

if [ "$INSTALL_SCHEDULER" = "1" ]; then
  SCHED_UNIT=/etc/systemd/system/modstore-scheduler.service
  if [ -f "$SCHED_UNIT" ]; then
    bak_sched="/tmp/modstore-scheduler.service.bak.$(date +%s)"
    cp -a "$SCHED_UNIT" "$bak_sched"
    echo "[ok] backed up $SCHED_UNIT -> $bak_sched"
  fi
  umask 022
  cat >"$SCHED_UNIT" <<EOF
# Generated by align_modstore_systemd_to_deploy.sh — 对齐 $DEPLOY_DIR
[Unit]
Description=MODstore Background Jobs (outbox + scheduler)
After=network.target modstore.service

[Service]
Type=simple
User=root
WorkingDirectory=$DEPLOY_DIR
EnvironmentFile=-$DEPLOY_DIR/.env
Environment=PYTHONUNBUFFERED=1
Environment=MODSTORE_RUN_BACKGROUND_JOBS=1
Environment=MODSTORE_BUS=rabbitmq
ExecStart=$DEPLOY_DIR/.venv/bin/python -m uvicorn modstore_server.app:app --host 127.0.0.1 --port 9990 --workers 1
Restart=on-failure
RestartSec=10

[Install]
WantedBy=multi-user.target
EOF
  systemctl daemon-reload
  systemctl enable modstore-scheduler
  systemctl restart modstore-scheduler
  sleep 2
  systemctl is-active modstore-scheduler || {
    echo "[err] modstore-scheduler not active; journalctl -u modstore-scheduler -n 80 --no-pager" >&2
    exit 1
  }
  echo "[ok] modstore-scheduler installed and running"
fi

echo "[ok] align done"
