#!/usr/bin/env python3
"""Build a human + machine readable routing table from yuangon employee.yaml files.

Used by `task-router-officer` to decide which employee should receive a task
based on `files_hint` matching `scope_globs` (and not matching `forbidden_globs`).

Output:
- MODstore_deploy/docs/routing-table.md  (human readable, with hit_count comments)
- MODstore_deploy/modstore_server/data/routing_table.json (machine readable, used at runtime)

Run modes:
- $ python -m scripts.build_routing_table          # write both files
- $ python -m scripts.build_routing_table --check  # exit code 1 if files would change

Triggered automatically by:
- `push-update-context-officer.skill-yuangon-resync` after onboard succeeds
- A daily cron at 03:00 (manifest schedule on `task-router-officer`)
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[2]
YUANGON_DIR = REPO_ROOT / "yuangon"
DOCS_OUT = REPO_ROOT / "MODstore_deploy" / "docs" / "routing-table.md"
JSON_OUT = REPO_ROOT / "MODstore_deploy" / "modstore_server" / "data" / "routing_table.json"


def _load_yaml(path: Path) -> dict[str, Any]:
    import yaml

    return yaml.safe_load(path.read_text(encoding="utf-8")) or {}


def _collect() -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for f in sorted(YUANGON_DIR.glob("**/employee.yaml")):
        d = _load_yaml(f)
        if not isinstance(d, dict):
            continue
        rows.append(
            {
                "id": str(d.get("id") or "").strip(),
                "name": str(d.get("name") or "").strip(),
                "area": str(d.get("area") or "").strip(),
                "domain": str(d.get("domain") or "").strip().splitlines()[:1] and " ".join(
                    str(d.get("domain") or "").split()
                )[:200],
                "scope_globs": [s for s in (d.get("scope_globs") or []) if isinstance(s, str) and s.strip()],
                "forbidden_globs": [
                    s for s in (d.get("forbidden_globs") or []) if isinstance(s, str) and s.strip()
                ],
                "depends_on": list(d.get("depends_on") or []),
                "subscribes": list(((d.get("triggers") or {}).get("subscribes") or [])),
                "version": str(d.get("version") or "1.0.0"),
                "yaml_path": str(f.relative_to(REPO_ROOT)).replace("\\", "/"),
            }
        )
    rows.sort(key=lambda r: (r["area"], r["id"]))
    return rows


def _render_md(rows: list[dict[str, Any]]) -> str:
    now = datetime.now(timezone.utc).isoformat(timespec="seconds")
    lines = [
        "# Routing Table",
        "",
        f"> Auto-generated by `scripts/build_routing_table.py` at {now}",
        f"> Source: `yuangon/**/employee.yaml`  ·  Total employees: {len(rows)}",
        "",
        "DO NOT edit by hand. To change ownership update the corresponding `employee.yaml`",
        "and re-run this script (or push, the git hook + push-update-context-officer take care).",
        "",
        "## Index",
        "",
        "| Area | Employee | Scope (top 3) | Subscribes |",
        "|------|----------|---------------|------------|",
    ]
    for r in rows:
        scope = "<br>".join(f"`{g}`" for g in r["scope_globs"][:3]) or "—"
        subs = ", ".join(f"`{s}`" for s in r["subscribes"]) or "—"
        lines.append(f"| {r['area']} | **{r['id']}** ({r['name']}) | {scope} | {subs} |")
    lines.append("")
    lines.append("## Detail")
    for r in rows:
        lines.append("")
        lines.append(f"### `{r['id']}` — {r['name']}")
        lines.append("")
        lines.append(f"- area: `{r['area']}`  ·  version: `{r['version']}`  ·  yaml: [`{r['yaml_path']}`](../../{r['yaml_path']})")
        if r["domain"]:
            lines.append(f"- domain: {r['domain']}")
        if r["depends_on"]:
            lines.append(f"- depends_on: {', '.join(f'`{x}`' for x in r['depends_on'])}")
        if r["subscribes"]:
            lines.append(f"- subscribes: {', '.join(f'`{x}`' for x in r['subscribes'])}")
        lines.append("- scope_globs:")
        for g in r["scope_globs"]:
            lines.append(f"  - `{g}`")
        if r["forbidden_globs"]:
            lines.append("- forbidden_globs:")
            for g in r["forbidden_globs"]:
                lines.append(f"  - `{g}`")
    return "\n".join(lines) + "\n"


def _render_json(rows: list[dict[str, Any]]) -> str:
    payload = {
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "employees": [
            {
                "id": r["id"],
                "area": r["area"],
                "scope_globs": r["scope_globs"],
                "forbidden_globs": r["forbidden_globs"],
                "subscribes": r["subscribes"],
                "depends_on": r["depends_on"],
            }
            for r in rows
        ],
    }
    return json.dumps(payload, indent=2, ensure_ascii=False) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0] if __doc__ else "")
    parser.add_argument("--check", action="store_true", help="Fail if outputs would change.")
    args = parser.parse_args()

    rows = _collect()
    md_text = _render_md(rows)
    json_text = _render_json(rows)

    DOCS_OUT.parent.mkdir(parents=True, exist_ok=True)
    JSON_OUT.parent.mkdir(parents=True, exist_ok=True)

    if args.check:
        old_md = DOCS_OUT.read_text(encoding="utf-8") if DOCS_OUT.exists() else ""
        old_json = JSON_OUT.read_text(encoding="utf-8") if JSON_OUT.exists() else ""
        if old_md.strip() != md_text.strip() or old_json.strip() != json_text.strip():
            print("[CHECK] routing table is stale; run without --check to regenerate", file=sys.stderr)
            return 1
        print("[CHECK] routing table is up-to-date")
        return 0

    DOCS_OUT.write_text(md_text, encoding="utf-8", newline="\n")
    JSON_OUT.write_text(json_text, encoding="utf-8", newline="\n")
    print(f"[OK] wrote {DOCS_OUT.relative_to(REPO_ROOT)} ({len(md_text)} bytes)")
    print(f"[OK] wrote {JSON_OUT.relative_to(REPO_ROOT)} ({len(json_text)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
