#!/usr/bin/env python3
"""将 SSH 拉取的生产 .env 改写为 Mac 本地日更可用（路径 + 开启 digest，禁提交 git）。"""
from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

_MANAGED_BEGIN = "# >>> daily-closure v10 (managed)"
_MANAGED_END = "# <<< daily-closure v10"

_SMTP_KEYS = (
    "MODSTORE_SMTP_HOST",
    "MODSTORE_SMTP_PORT",
    "MODSTORE_SMTP_USER",
    "MODSTORE_SMTP_PASSWORD",
    "MODSTORE_SENDER_EMAIL",
    "MODSTORE_SENDER_NAME",
    "MODSTORE_DAILY_DIGEST_EMAIL",
    "MODSTORE_EMAIL_DEBUG",
    "MODSTORE_IMAP_HOST",
    "MODSTORE_IMAP_PORT",
    "MODSTORE_IMAP_USER",
    "MODSTORE_IMAP_PASSWORD",
    "MODSTORE_SURFACE_AUDIT_USER",
    "MODSTORE_SURFACE_AUDIT_PASSWORD",
)

_PG_KEYS = (
    "DATABASE_URL",
    "DATABASE_USER",
    "DATABASE_PASSWORD",
    "DATABASE_HOST",
    "DATABASE_PORT",
    "DATABASE_NAME",
)

_REDIS_KEYS = (
    "REDIS_URL",
    "REDIS_PORT",
    "MODSTORE_REDIS_URL",
    "MODSTORE_EVENT_STREAM_URL",
    "CACHE_REDIS_URL",
    "XCAGI_REDIS_URL",
    "MODSTORE_VECTOR_REDIS_URL",
)

_LOCAL_BLOCK = """# >>> local-mac overrides (pull_prod_env_for_local)
MODSTORE_AUTOMATION_PRIMARY=local_mac
MODSTORE_AUTOMATION_ROLE=local_mac
MODSTORE_DAILY_ORCHESTRATOR_DIGEST_MODE=primary
MODSTORE_DAILY_ORCHESTRATOR_ENABLED=1
MODSTORE_DAILY_DIGEST_ENABLED=1
MODSTORE_DAILY_MEETING_ENABLED=1
MODSTORE_DAILY_VIBE_PREP_ENABLED=1
MODSTORE_DAILY_VIBE_LINE_DISPATCH_ENABLED=1
MODSTORE_DAILY_VIBE_EXECUTE_ENABLED=1
MODSTORE_RELEASE_TRAIN_ENABLED=1
MODSTORE_DAILY_SURFACE_AUDIT_ENABLED=1
MODSTORE_DAILY_SURFACE_PPT_ENABLED=1
MODSTORE_SURFACE_AUDIT_AUTO_START=1
MODSTORE_SURFACE_AUDIT_ANDROID=1
MODSTORE_DAILY_SURFACE_AUDIT_MODE=daily
MODSTORE_DAILY_SURFACE_AUDIT_MAX_PER_LANE=1
MODSTORE_SURFACE_AUDIT_SKIP_CATALOG=0
MODSTORE_SURFACE_AUDIT_CATALOG_MAX=3
MODSTORE_SURFACE_AUDIT_STOP_AFTER=1
MODSTORE_DR_PROBE_ENABLED=1
MODSTORE_ONDEMAND_BACKUP_ENABLED=1
MODSTORE_RUN_BACKGROUND_JOBS=1
MODSTORE_EMAIL_DEBUG=0
MODSTORE_EVENT_STREAM_ENABLED=0
# <<< local-mac overrides (pull_prod_env_for_local)
"""


def _strip_managed_block(text: str) -> str:
    while _MANAGED_BEGIN in text:
        pre, rest = text.split(_MANAGED_BEGIN, 1)
        _, post = rest.split(_MANAGED_END, 1)
        text = pre + post
    return text


def _parse_env(text: str) -> dict[str, str]:
    out: dict[str, str] = {}
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in raw:
            continue
        k, v = raw.split("=", 1)
        out[k.strip()] = v
    return out


def _render_env(values: dict[str, str], *, header: str) -> str:
    lines = [header.rstrip(), ""]
    for k in sorted(values.keys()):
        lines.append(f"{k}={values[k]}")
    return "\n".join(lines).rstrip() + "\n"


def localize(
    raw_text: str,
    *,
    local_root: Path,
    modstore_port: str = "8788",
) -> tuple[str, str]:
    local_root = local_root.expanduser().resolve()
    text = _strip_managed_block(raw_text)
    text = text.replace("/root/XCMAX", str(local_root))
    text = text.replace("/root/modstore-git", str(local_root / "成都修茈科技有限公司" / "MODstore_deploy"))

    values = _parse_env(text)
    modstore_db = local_root / "成都修茈科技有限公司" / "MODstore_deploy" / "modstore_server" / "modstore.db"
    for k in _PG_KEYS + _REDIS_KEYS:
        values.pop(k, None)
    values["MODSTORE_DB_PATH"] = str(modstore_db)
    values["XCMAX_MONOREPO_ROOT"] = str(local_root)
    values["MODSTORE_REPO_ROOT"] = str(local_root)
    values["MODSTORE_RELEASE_TRAIN_JSON"] = str(local_root / "FHD" / "config" / "release_train.json")
    values["MODSTORE_DEPLOY_HEALTH_URL"] = f"http://127.0.0.1:{modstore_port}/api/health"
    values["MODSTORE_API_PORT"] = modstore_port
    local_modstore = f"http://127.0.0.1:{modstore_port}"
    values["MODSTORE_INTERNAL_API_BASE"] = local_modstore
    values["XCAGI_MARKET_BASE_URL"] = local_modstore
    values["MODSTORE_LOCAL_BASE_URL"] = local_modstore
    values["MODSTORE_DIGEST_BASE_URL"] = local_modstore
    values["MODSTORE_ALL_HANDS_BASE_URL"] = local_modstore
    values["MODSTORE_EVENT_STREAM_ENABLED"] = "0"
    values.pop("MODSTORE_DAILY_ORCHESTRATOR_DIGEST_MODE", None)

    for line in _LOCAL_BLOCK.splitlines():
        s = line.strip()
        if not s or s.startswith("#") or "=" not in s:
            continue
        k, v = s.split("=", 1)
        values[k.strip()] = v

    synced_header = (
        "# AUTO-GENERATED by pull_prod_env_for_local.sh — DO NOT COMMIT\n"
        f"# source: production .env localized for {local_root}\n"
    )
    smtp_vals = {k: values[k] for k in _SMTP_KEYS if k in values and str(values[k]).strip()}
    smtp_header = (
        "# AUTO-GENERATED SMTP/IMAP slice — DO NOT COMMIT\n"
        "# Used by run_modstore_daily_local.sh after .env.production.synced\n"
    )
    synced_body = _render_env(values, header=synced_header + _LOCAL_BLOCK)
    smtp_body = _render_env(smtp_vals, header=smtp_header) if smtp_vals else ""
    return synced_body, smtp_body


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--in", dest="in_path", type=Path, required=True)
    p.add_argument("--synced-out", type=Path, required=True)
    p.add_argument("--smtp-out", type=Path, required=True)
    p.add_argument(
        "--local-root",
        type=Path,
        default=Path(os.environ.get("XCMAX_MONOREPO_ROOT", Path(__file__).resolve().parents[3])),
    )
    p.add_argument("--port", default=os.environ.get("MODSTORE_PORT", "8788"))
    args = p.parse_args()

    raw = args.in_path.read_text(encoding="utf-8", errors="replace")
    synced, smtp = localize(raw, local_root=args.local_root, modstore_port=str(args.port))
    args.synced_out.parent.mkdir(parents=True, exist_ok=True)
    args.synced_out.write_text(synced, encoding="utf-8")
    os.chmod(args.synced_out, 0o600)
    if smtp.strip():
        args.smtp_out.write_text(smtp, encoding="utf-8")
        os.chmod(args.smtp_out, 0o600)
        print(f"wrote {args.smtp_out} ({len(smtp.splitlines())} lines)")
    else:
        print("WARN: no SMTP keys in pulled env — check server .env", file=sys.stderr)
    print(f"wrote {args.synced_out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
