"""Shared dotenv loading for MODstore runtime processes."""

from __future__ import annotations

import os
from pathlib import Path
from typing import Iterable

_PROCESS_RUNTIME_ENV_KEYS = (
    "DATABASE_URL",
    "MODSTORE_DB_PATH",
    "MODSTORE_RUNTIME_STATE_ROOT",
    "MODSTORE_RUNTIME_DB_PATH",
    "MODSTORE_RUNTIME_DIR",
    "MODSTORE_EVENT_OUTBOX_PATH",
    "MODSTORE_WEBHOOK_EVENTS_DIR",
    "MODSTORE_RUNTIME_CONFIG_ROOT",
    "MODSTORE_RELEASE_TRAIN_JSON",
    "MODSTORE_TIME_RAIL_GRAPH_JSON",
    "MODSTORE_TIME_RAIL_RUNTIME_JSON",
    "MODSTORE_POST_DEPLOY_SMOKE_STATE_FILE",
    "MODSTORE_SURFACE_AUDIT_AUTO_START",
    "MODSTORE_SURFACE_AUDIT_ANDROID",
    "MODSTORE_SURFACE_AUDIT_PS_ENABLED",
    "MODSTORE_SURFACE_AUDIT_PS_BASE_URL",
    "MODSTORE_SURFACE_AUDIT_PIDS_DIR",
    "MODSTORE_SURFACE_AUDIT_LOG_DIR",
    "MODSTORE_SURFACE_AUDIT_STATE_ROOT",
    "MODSTORE_DAILY_SURFACE_AUDIT_BASE_URL",
    "MODSTORE_DAILY_SURFACE_AUDIT_MODE",
    "MODSTORE_DAILY_SURFACE_AUDIT_MAX_PER_LANE",
    "SURFACE_AUDIT_API_URL",
    "SURFACE_AUDIT_ANDROID_FHD_HOST",
    "SURFACE_AUDIT_ANDROID_ADB",
    "XCAGI_FHD_ROOT",
    "XCAGI_ANDROID_SDK_ROOT",
    "XCAGI_ANDROID_EMULATOR_PID_FILE",
    "XCAGI_ANDROID_EMULATOR_LOG_FILE",
    "MODSTORE_ANDROID_EMULATOR_START_SCRIPT",
    "ANDROID_HOME",
    "ANDROID_SDK_ROOT",
)


def _load_plain_env(path: Path, *, override: bool) -> bool:
    if not path.is_file():
        return False
    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        return False
    for line in text.splitlines():
        s = line.strip()
        if not s or s.startswith("#") or "=" not in s:
            continue
        key, _, val = s.partition("=")
        key = key.strip()
        val = val.strip().strip('"').strip("'")
        if key and (override or key not in os.environ):
            os.environ[key] = val
    return True


def _load_dotenv_file(path: Path, *, override: bool) -> bool:
    if not path.is_file():
        return False
    try:
        from dotenv import load_dotenv

        return bool(load_dotenv(path, override=override))
    except ImportError:
        return _load_plain_env(path, override=override)


def load_modstore_env(
    deploy_root: Path | None = None,
    *,
    include_synced: bool | None = None,
    include_local: bool | None = None,
    preserve_existing: Iterable[str] = (),
) -> list[str]:
    """Load MODstore env files in local/production-compatible order.

    Order: .env -> .env.production.synced -> .env.local.
    The synced file is generated by scripts/pull_prod_env_for_local.sh and carries
    the real SMTP/scheduler values used by the local daily automation stack.
    """
    root = (deploy_root or Path(__file__).resolve().parent.parent).resolve()
    pytest_mode = (os.environ.get("MODSTORE_PYTEST_USE_SQLITE") or "").strip() == "1"
    if include_synced is None:
        include_synced = not pytest_mode
    if include_local is None:
        include_local = not pytest_mode
    protected = tuple(dict.fromkeys((*_PROCESS_RUNTIME_ENV_KEYS, *preserve_existing)))
    preserved = {key: os.environ.get(key) for key in protected if os.environ.get(key)}
    loaded: list[str] = []
    candidates = [(".env", False)]
    if include_synced:
        candidates.append((".env.production.synced", True))
    if include_local:
        candidates.append((".env.local", True))
    for name, override in candidates:
        path = root / name
        if _load_dotenv_file(path, override=override):
            loaded.append(str(path))
    for key, value in preserved.items():
        os.environ[key] = value
    return loaded


__all__ = ["load_modstore_env"]
