"""Immutable seed rows for MODstore database initialization."""

from __future__ import annotations

DEFAULT_PLAN_TEMPLATES = (
    {
        "id": "plan_basic",
        "name": "VIP",
        "description": "入门会员，解锁基础 AI 调用与平台能力",
        "price": 9.90,
        "features_json": '["基础 AI 对话","基础模型额度","可购买更多余额","会员身份标识"]',
        "quotas_json": '{"employee_count":1,"storage_mb":512}',
    },
    {
        "id": "plan_pro",
        "name": "VIP+",
        "description": "进阶会员，更高额度 + BYOK + 用量明细",
        "price": 29.90,
        "features_json": '["更高 AI 调用额度","BYOK 自有密钥","优先模型接入","用量明细","高级功能优先体验"]',
        "quotas_json": '{"employee_count":3,"storage_mb":2048}',
    },
    {
        "id": "plan_enterprise",
        "name": "svip",
        "description": "企业级会员（svip），含大额度企业 AI 调用、团队/部署 与优先支持",
        "price": 99.90,
        "features_json": '["企业级 AI 调用额度","团队/企业支持","专属部署支持","优先技术支持"]',
        "quotas_json": '{"employee_count":999999,"storage_mb":10240}',
    },
    {
        "id": "plan_svip2",
        "name": "SVIP2",
        "description": "SVIP 进阶档（需已是 SVIP 用户）",
        "price": 199.00,
        "features_json": '["svip 全部权益","双倍 AI 调用额度","专属客服群组","新功能内测资格"]',
        "quotas_json": '{"employee_count":999999,"storage_mb":20480}',
    },
    {
        "id": "plan_svip3",
        "name": "SVIP3",
        "description": "SVIP 进阶档（需已是 SVIP 用户）",
        "price": 299.00,
        "features_json": '["SVIP2 全部权益","三倍 AI 调用额度","定制工作流模板"]',
        "quotas_json": '{"employee_count":999999,"storage_mb":30720}',
    },
    {
        "id": "plan_svip4",
        "name": "SVIP4",
        "description": "SVIP 进阶档（需已是 SVIP 用户）",
        "price": 499.00,
        "features_json": '["SVIP3 全部权益","五倍 AI 调用额度","专家咨询时长 2h/月"]',
        "quotas_json": '{"employee_count":999999,"storage_mb":51200}',
    },
    {
        "id": "plan_svip5",
        "name": "SVIP5",
        "description": "SVIP 进阶档（需已是 SVIP 用户）",
        "price": 999.00,
        "features_json": '["SVIP4 全部权益","十倍 AI 调用额度","专家咨询时长 5h/月"]',
        "quotas_json": '{"employee_count":999999,"storage_mb":102400}',
    },
    {
        "id": "plan_svip6",
        "name": "SVIP6",
        "description": "SVIP 进阶档（需已是 SVIP 用户）",
        "price": 1999.00,
        "features_json": '["SVIP5 全部权益","二十倍 AI 调用额度","驻场技术对接 1d/月"]',
        "quotas_json": '{"employee_count":999999,"storage_mb":204800}',
    },
    {
        "id": "plan_svip7",
        "name": "SVIP7",
        "description": "SVIP 进阶档（需已是 SVIP 用户）",
        "price": 2999.00,
        "features_json": '["SVIP6 全部权益","三十倍 AI 调用额度","驻场技术对接 2d/月","品牌联合露出"]',
        "quotas_json": '{"employee_count":999999,"storage_mb":307200}',
    },
    {
        "id": "plan_svip8",
        "name": "SVIP8",
        "description": "SVIP 顶级档（需已是 SVIP 用户）",
        "price": 4999.00,
        "features_json": '["SVIP7 全部权益","无限 AI 调用额度","驻场技术对接 5d/月","战略合作通道"]',
        "quotas_json": '{"employee_count":999999,"storage_mb":1048576}',
    },
)

DEFAULT_CUSTOMER_SERVICE_STANDARDS = (
    {
        "name": "订单退款自动处理",
        "scenario": "refund",
        "description": "识别订单退款诉求，低风险且证据完整时自动创建退款工单。",
        "rules_json": '{"required_fields":["order_no","reason"],"max_auto_amount":100,"deny_if":["order_not_paid","duplicate_refund"]}',
        "action_policy_json": '{"auto_actions":["refund.apply"],"high_risk_actions":["refund.approve"],"requires_audit_log":true}',
        "risk_level": "medium",
        "priority": 10,
    },
    {
        "name": "商品投诉与合规审核",
        "scenario": "catalog_complaint",
        "description": "处理抄袭、侵权、授权争议、无法下载等市场商品问题。",
        "rules_json": '{"required_fields":["catalog_id","complaint_type","reason"],"evidence_recommended":true}',
        "action_policy_json": '{"auto_actions":["catalog.complaint.create"],"high_risk_actions":["catalog.compliance.update"],"requires_audit_log":true}',
        "risk_level": "medium",
        "priority": 20,
    },
    {
        "name": "上架合规审核",
        "scenario": "catalog_review",
        "description": "根据素材来源、授权范围、IP 风险与收费策略进行上架合规判断。",
        "rules_json": '{"required_fields":["catalog_id"],"reject_if":["paid_without_commercial_license","high_ip_risk_paid"]}',
        "action_policy_json": '{"auto_actions":["catalog.compliance.review"],"requires_audit_log":true}',
        "risk_level": "high",
        "priority": 30,
    },
    {
        "name": "账号权益与使用咨询",
        "scenario": "account_support",
        "description": "回答账号、会员、下载、额度和权益问题，必要时生成客服工单。",
        "rules_json": '{"required_fields":[],"knowledge_first":true}',
        "action_policy_json": '{"auto_actions":["ticket.note"],"requires_audit_log":true}',
        "risk_level": "low",
        "priority": 40,
    },
)
