"""已注册工作流工具：按 tool_id 路由到实现（自 tools_execution_service 拆分）。"""

from __future__ import annotations

from app.services.tools_workflow_registered.business import _registered_router_normal_slot_dispatch as _registered_router_normal_slot_dispatch
from app.services.tools_workflow_registered.business import _registered_router_customers as _registered_router_customers
from app.services.tools_workflow_registered.business import _registered_router_products as _registered_router_products
from app.services.tools_workflow_registered.business import _registered_router_materials as _registered_router_materials
from app.services.tools_workflow_registered.business import _registered_router_inventory as _registered_router_inventory
from app.services.tools_workflow_registered.business import _registered_router_purchase as _registered_router_purchase
from app.services.tools_workflow_registered.business import _registered_router_finance as _registered_router_finance
from app.services.tools_workflow_registered.business import _registered_router_shipment_records as _registered_router_shipment_records
from app.services.tools_workflow_registered.business import _registered_router_shipment_orders as _registered_router_shipment_orders
from app.services.tools_workflow_registered.business import _registered_router_business_docking_family as _registered_router_business_docking_family
from app.services.tools_workflow_registered.business import _registered_router_business_event as _registered_router_business_event
from app.services.tools_workflow_registered.business import _registered_router_system_maintenance as _registered_router_system_maintenance
from app.services.tools_workflow_registered.excel import _registered_router_excel_analyzer as _registered_router_excel_analyzer
from app.services.tools_workflow_registered.excel import _registered_router_excel_toolkit as _registered_router_excel_toolkit
from app.services.tools_workflow_registered.excel import _registered_router_label_template_generator as _registered_router_label_template_generator
from app.services.tools_workflow_registered.excel import _registered_router_document_template as _registered_router_document_template
from app.services.tools_workflow_registered.excel import _registered_router_template_preview as _registered_router_template_preview
from app.services.tools_workflow_registered.misc import _registered_router_wechat as _registered_router_wechat
from app.services.tools_workflow_registered.misc import _registered_router_print as _registered_router_print
from app.services.tools_workflow_registered.misc import _registered_router_printer_list as _registered_router_printer_list
from app.services.tools_workflow_registered.misc import _registered_router_settings as _registered_router_settings
from app.services.tools_workflow_registered.misc import _registered_router_employee as _registered_router_employee
from app.services.tools_workflow_registered.misc import _BUSINESS_DB_ENTITY_ALIASES as _BUSINESS_DB_ENTITY_ALIASES
from app.services.tools_workflow_registered.misc import _normalize_business_db_entity as _normalize_business_db_entity
from app.services.tools_workflow_registered.misc import _registered_router_business_db as _registered_router_business_db
from app.services.tools_workflow_registered.rag import _registered_router_dataset_rag as _registered_router_dataset_rag
from app.services.tools_workflow_registered.rag import _registered_router_memory_v2 as _registered_router_memory_v2
from app.services.tools_workflow_registered.excel_advanced import _registered_router_excel_analysis as _registered_router_excel_analysis
from app.services.tools_workflow_registered.excel_advanced import _registered_router_generate_office_document as _registered_router_generate_office_document
from app.services.tools_workflow_registered.excel_advanced import _registered_router_excel_vector_index as _registered_router_excel_vector_index
from app.services.tools_workflow_registered.excel_advanced import _ocr_artifact_payload as _ocr_artifact_payload
from app.services.tools_workflow_registered.excel_advanced import _registered_router_ocr as _registered_router_ocr
from app.services.tools_workflow_registered.excel_advanced import _execute_excel_import_records as _execute_excel_import_records
from app.services.tools_workflow_registered.excel_advanced import _registered_router_excel_import as _registered_router_excel_import
from app.services.tools_workflow_registered.excel_advanced import _registered_router_unit_products_import as _registered_router_unit_products_import
from app.services.tools_workflow_registered.core import _WorkflowRouterMap as _WorkflowRouterMap
from app.services.tools_workflow_registered.core import _REGISTERED_WORKFLOW_ROUTERS as _REGISTERED_WORKFLOW_ROUTERS
from app.services.tools_workflow_registered.core import execute_registered_workflow_tool as execute_registered_workflow_tool
