"""Stable OpenAPI metadata for the MODstore application factory."""

OPENAPI_TAGS = [
    {"name": "health", "description": "服务探活"},
    {
        "name": "config",
        "description": "库路径、XCAGI 根目录、后端 URL、导出 FHD 壳层 /api/mods JSON",
    },
    {"name": "mods", "description": "Mod 列表、详情、manifest、文件读写、导入导出"},
    {"name": "sync", "description": "与 XCAGI/mods 推送与拉回"},
    {"name": "debug", "description": "沙箱目录、primary 批量标记、XCAGI 状态代理"},
    {
        "name": "authoring",
        "description": "扩展面文档、蓝图路由静态扫描、宿主 OpenAPI 合并",
    },
    {"name": "payment", "description": "支付、订单与会员计划"},
    {
        "name": "workflow",
        "description": "工作流编排、执行、自然语言生成与沙箱（见 workflow_api / workflow_nl_graph）",
    },
    {
        "name": "workflow-hooks",
        "description": "工作流 Webhook 触发入口（/api/workflow-hooks）",
    },
    {"name": "webhooks", "description": "业务 Webhook 投递与重放"},
    {"name": "inbound-webhooks", "description": "入站 Webhook 接收"},
    {"name": "refunds", "description": "退款申请与审核"},
    {"name": "catalog", "description": "公开目录与市场检索"},
    {
        "name": "catalog-mod-sync",
        "description": "公网机器令牌：库与 XCAGI/mods 推送/拉回（/v1/mod-sync）",
    },
    {
        "name": "market",
        "description": "市场展示、目录与匿名公开接口（如落地页联系表单）",
    },
    {
        "name": "auth",
        "description": "注册、登录、JWT、个人资料；与 Java 支付侧用户叠加信息",
    },
    {
        "name": "admin",
        "description": "需管理员权限的账户与运维辅助入口（与 /api/admin/* 部分重叠）",
    },
    {
        "name": "employees",
        "description": "AI 员工执行、配置与打包（领域边界见 SERVICE_BOUNDARIES.md）",
    },
    {"name": "llm", "description": "大模型目录、BYOK、聊天/多模态代理与计费"},
    {
        "name": "openai-gateway",
        "description": "OpenAI 兼容聚合网关（/v1/chat/completions，账户默认路由 + 平台计费）",
    },
    {"name": "knowledge", "description": "知识库与向量检索（v1 API）"},
    {"name": "knowledge-v2", "description": "知识库 v2 扩展接口"},
    {"name": "workbench", "description": "工作台与制作向导相关 API"},
    {"name": "eskills", "description": "ESkill 定义与版本"},
    {"name": "script-workflow", "description": "脚本化工作流"},
    {"name": "realtime", "description": "WebSocket 实时通知通道（/api/realtime/ws）"},
    {"name": "notifications", "description": "站内通知 REST 与持久化"},
    {"name": "openapi-connectors", "description": "第三方 OpenAPI 连接器导入与调用"},
    {"name": "customer-service", "description": "客服编排与工具链"},
    {"name": "butler", "description": "数字管家（Butler）编排 API"},
    {"name": "butler-qq", "description": "Butler ↔ QQ 官方机器人 HTTP 桥"},
    {"name": "butler-qqbot", "description": "Butler QQ botpy 网关与 Webhook"},
    {"name": "developer", "description": "开发者门户与密钥"},
    {"name": "key-export", "description": "开发者密钥导出"},
    {"name": "sandbox", "description": "沙箱执行与校验"},
    {"name": "ops", "description": "运维状态、编排开关与员工健康"},
    {"name": "analytics", "description": "埋点与分析"},
    {"name": "templates", "description": "模板资源"},
    {"name": "csp", "description": "CSP 违规上报"},
    {"name": "runtime-allowlist", "description": "运行时允许名单（管理）"},
    {"name": "admin-events", "description": "管理端领域事件查询"},
    {"name": "admin-email", "description": "管理端邮件测试与配置"},
    {"name": "admin-employees", "description": "管理端员工执行指标与干预"},
    {"name": "admin-change-requests", "description": "员工变更请求审批"},
    {"name": "admin-ai-accounts", "description": "AI 员工账户与凭据（管理）"},
    {"name": "admin-yuangon-onboard", "description": "元工（Yuangon）入驻配置"},
    {"name": "admin-employee-autonomy", "description": "员工自主度策略"},
    {"name": "admin-ops", "description": "运维审计与操作记录"},
    {"name": "admin-duty-graph", "description": "值班员工关系图（管理）"},
    {
        "name": "admin-production-line",
        "description": "制作线全流程管理（10步端到端编排与审批）",
    },
    {
        "name": "admin-redline",
        "description": "红线审批门控（支付/安全/DB/发布/删除 AI执行+人工审批）",
    },
    {"name": "author-earnings", "description": "作者分成与结算相关"},
    {"name": "invoices", "description": "发票"},
    {"name": "reconciliation", "description": "对账"},
    {"name": "subscription", "description": "订阅续费与计划"},
    {
        "name": "xcmax-admin",
        "description": "XCmax 服务器后台与双向同步（/api/xcmax/admin、/api/xcmax/sync）",
    },
]
