#!/usr/bin/env python3
"""
CI gate: parse neuro usage JSON and enforce minimum Application-layer Neuro-DDD adoption.

Baseline file (optional): docs/reports/neuro_usage_baseline.json
Generated by: python scripts/dev/analyze/analyze_neuro_usage.py --json docs/reports/neuro_usage_latest.json
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def load_report(path: Path) -> dict:
    with path.open(encoding="utf-8") as f:
        return json.load(f)


def check_thresholds(
    report: dict,
    *,
    min_app_pct: float,
    min_core_domains_v2: int,
    baseline: dict | None,
) -> list[str]:
    errors: list[str] = []
    layers = report.get("layers") or {}
    app = layers.get("application") or {}
    app_pct = float(app.get("neuro_pct") or 0.0)
    if app_pct < min_app_pct:
        errors.append(
            f"Application 层 Neuro 使用率 {app_pct:.1f}% 低于阈值 {min_app_pct:.1f}%"
        )

    migrated = report.get("migrated_http_domains") or []
    if len(migrated) < min_core_domains_v2:
        errors.append(
            f"已迁移 HTTP 核心域 {len(migrated)} < {min_core_domains_v2} "
            f"(当前: {migrated})"
        )

    if baseline:
        base_layers = (baseline.get("layers") or {}).get("application") or {}
        base_pct = float(base_layers.get("neuro_pct") or 0.0)
        if app_pct + 1e-6 < base_pct:
            errors.append(
                f"Application 层使用率 {app_pct:.1f}% 低于基线 {base_pct:.1f}%（只升不降）"
            )
    return errors


def main() -> int:
    root = _repo_root()
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--report",
        default=str(root / "docs/reports/neuro_usage_latest.json"),
        help="JSON report from analyze_neuro_usage.py",
    )
    parser.add_argument(
        "--baseline",
        default=str(root / "docs/reports/neuro_usage_baseline.json"),
        help="Optional baseline JSON for non-regression check",
    )
    parser.add_argument("--min-app-pct", type=float, default=1.0)
    parser.add_argument("--min-core-domains", type=int, default=4)
    args = parser.parse_args()

    report_path = Path(args.report)
    if not report_path.is_file():
        print(f"ERROR: report not found: {report_path}", file=sys.stderr)
        return 2

    report = load_report(report_path)
    baseline = None
    baseline_path = Path(args.baseline)
    if baseline_path.is_file():
        baseline = load_report(baseline_path)

    errors = check_thresholds(
        report,
        min_app_pct=args.min_app_pct,
        min_core_domains_v2=args.min_core_domains,
        baseline=baseline,
    )
    if errors:
        for err in errors:
            print(f"::error::{err}")
        return 1

    layers = report.get("layers") or {}
    app_pct = (layers.get("application") or {}).get("neuro_pct", 0)
    print(f"OK: application neuro_pct={app_pct}% migrated_domains={report.get('migrated_http_domains')}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
