name: xcagi_flutter_poc
description: Android-first Flutter POC for XCAGI mobile core flows.
publish_to: "none"
version: 1.0.0+10

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  camera: ^0.12.0+1
  flutter:
    sdk: flutter
  google_mlkit_barcode_scanning: ^0.14.2
  image_picker: ^1.2.2
  speech_to_text: ^7.4.0
  url_launcher: ^6.3.2
  web_socket_channel: ^3.0.2
  webview_flutter: ^4.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/avatars/
    - assets/brand/
    - android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
