from __future__ import annotations

from typing import Any

SPECIAL_OUTPUT_SCHEMAS_PART_2: dict[tuple[str, str], dict[str, Any]] = {
    ("excel_vector_index", "execute"): {
        "type": "object",
        "required": ["success", "index_id"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "index_id": {"type": "string"},
            "excel_vector_index_id": {"type": "string"},
            "excel_index_id": {"type": "string"},
            "chunk_count": {"type": "integer"},
            "row_count": {"type": "integer"},
            "error": {"type": "string"},
        },
    },
    ("excel_vector_index", "query"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "index_id": {"type": "string"},
            "query": {"type": "string"},
            "hits": {"type": "array"},
            "error": {"type": "string"},
        },
    },
    ("ocr", "recognize"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "text": {"type": "string"},
            "file_path": {"type": "string"},
            "confidence": {"type": "number"},
            "artifacts": {"type": "array"},
            "error_code": {"type": "string"},
        },
    },
    ("ocr", "request"): {
        "type": "object",
        "required": ["success", "request_id", "event", "published"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "request_id": {"type": "string"},
            "image_url": {"type": "string"},
            "ocr_type": {"type": "string"},
            "user_id": {"type": "string"},
            "event": {"type": "string"},
            "published": {"type": "boolean"},
            "error_code": {"type": "string"},
        },
    },
    ("ocr", "extract"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "data": {"type": "object"},
            "error_code": {"type": "string"},
        },
    },
    ("ocr", "analyze"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "data": {"type": "object"},
            "error_code": {"type": "string"},
        },
    },
    ("ocr", "recognize_and_extract"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "text": {"type": "string"},
            "data": {"type": "object"},
            "analysis": {"type": "object"},
            "artifacts": {"type": "array"},
            "error_code": {"type": "string"},
        },
    },
    ("shipment_records", "create"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "data": {"type": "object"},
            "record_id": {"type": "integer"},
            "order_id": {"type": "integer"},
            "error": {"type": "string"},
        },
    },
    ("shipment_records", "update"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "data": {"type": "object"},
            "error": {"type": "string"},
        },
    },
    ("shipment_records", "delete"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "deleted_count": {"type": "integer"},
            "data": {"type": "object"},
            "error": {"type": "string"},
        },
    },
    ("shipment_orders", "generate"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "file_path": {"type": "string"},
            "doc_name": {"type": "string"},
            "record_id": {"type": "integer"},
            "order_id": {"type": "integer"},
            "data": {"type": "object"},
            "error": {"type": "string"},
        },
    },
    ("shipment_orders", "generate_batch"): {
        "type": "object",
        "required": ["success", "data"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "data": {"type": "object"},
            "error": {"type": "string"},
        },
    },
    ("shipment_orders", "print"): {
        "type": "object",
        "required": ["success", "file_path", "updated"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "file_path": {"type": "string"},
            "updated": {"type": "boolean"},
            "printed_at": {"type": "string"},
            "warning": {"type": "string"},
            "error": {"type": "string"},
        },
    },
    ("shipment_orders", "clear_shipment"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "purchase_unit": {"type": "string"},
            "cleared_count": {"type": "integer"},
            "deleted_count": {"type": "integer"},
            "data": {"type": "object"},
            "error": {"type": "string"},
        },
    },
    ("shipment_orders", "set_sequence"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "sequence": {"type": "integer"},
            "data": {"type": "object"},
            "error": {"type": "string"},
        },
    },
    ("shipment_orders", "reset_sequence"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "sequence": {"type": "integer"},
            "data": {"type": "object"},
            "error": {"type": "string"},
        },
    },
    ("shipment_orders", "clear_all"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "cleared_count": {"type": "integer"},
            "deleted_count": {"type": "integer"},
            "data": {"type": "object"},
            "error": {"type": "string"},
        },
    },
    ("shipment_orders", "delete"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "deleted_id": {"type": "integer"},
            "deleted_count": {"type": "integer"},
            "data": {"type": "object"},
            "error": {"type": "string"},
        },
    },
    ("print", "print_document"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "file_path": {"type": "string"},
            "printer": {},
            "printer_name": {"type": "string"},
            "status": {"type": "string"},
            "job_id": {"type": "string"},
            "error_code": {"type": "string"},
            "error": {"type": "string"},
        },
    },
    ("print", "print_label"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "file_path": {"type": "string"},
            "printer": {},
            "printer_name": {"type": "string"},
            "copies": {"type": "integer"},
            "status": {"type": "string"},
            "require_confirm": {"type": "boolean"},
            "job_id": {"type": "string"},
            "error_code": {"type": "string"},
            "error": {"type": "string"},
        },
    },
    ("print", "test"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "printer_name": {"type": "string"},
            "status": {"type": "string"},
            "error_code": {"type": "string"},
            "error": {"type": "string"},
        },
    },
    ("print", "save_printer_selection"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "selection": {"type": "object"},
            "document_printer": {"type": "string"},
            "label_printer": {"type": "string"},
            "document": {},
            "label": {},
            "error_code": {"type": "string"},
            "error": {"type": "string"},
        },
    },
    ("print", "workflow_label_dispatch"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "model_number": {"type": "string"},
            "product_name": {"type": "string"},
            "quantity": {"type": "integer"},
            "file_path": {"type": "string"},
            "status": {"type": "string"},
            "job_id": {"type": "string"},
            "error_code": {"type": "string"},
            "error": {"type": "string"},
        },
    },
    ("business_event", "print_label"): {
        "type": "object",
        "required": ["success", "job_id", "event"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "job_id": {"type": "string"},
            "event": {"type": "string"},
        },
    },
    ("business_event", "inventory_update"): {
        "type": "object",
        "required": ["success", "event"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "event": {"type": "string"},
        },
    },
    ("business_event", "shipment_create"): {
        "type": "object",
        "required": ["success", "event", "published"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "event": {"type": "string"},
            "published": {"type": "boolean"},
        },
    },
    ("system_maintenance", "set_default_printer"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "data": {"type": "object"},
            "http_status_code": {"type": "integer"},
        },
    },
    ("system_maintenance", "enable_startup"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "data": {"type": "object"},
            "http_status_code": {"type": "integer"},
        },
    },
    ("system_maintenance", "disable_startup"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "data": {"type": "object"},
            "http_status_code": {"type": "integer"},
        },
    },
    ("system_maintenance", "backup_database"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "backup_file": {"type": "string"},
            "data": {"type": "object"},
            "http_status_code": {"type": "integer"},
        },
    },
    ("system_maintenance", "delete_database_backup"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "backup_file": {"type": "string"},
            "http_status_code": {"type": "integer"},
        },
    },
    ("system_maintenance", "restore_database"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "backup_file": {"type": "string"},
            "http_status_code": {"type": "integer"},
        },
    },
    ("system_maintenance", "clear_performance_cache"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "http_status_code": {"type": "integer"},
        },
    },
    ("system_maintenance", "invalidate_performance_cache"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "data": {"type": "object"},
            "http_status_code": {"type": "integer"},
        },
    },
    ("system_maintenance", "reinitialize_performance"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "data": {"type": "object"},
            "http_status_code": {"type": "integer"},
        },
    },
    ("excel_analysis", "read"): {
        "type": "object",
        "required": ["success", "data"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "data": {"type": "object"},
        },
    },
    ("excel_analysis", "query"): {
        "type": "object",
        "required": ["success", "data"],
        "properties": {
            "success": {"type": "boolean"},
            "answer": {"type": "string"},
            "data": {"type": "object"},
        },
    },
}
