from __future__ import annotations

from typing import Any

SPECIAL_OUTPUT_SCHEMAS_PART_3: dict[tuple[str, str], dict[str, Any]] = {
    ("excel_analyzer", "analyze"): {
        "type": "object",
        "required": ["success", "file_path"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "file_path": {"type": "string"},
            "file": {"type": "string"},
            "sheet": {"type": "string"},
            "structure": {"type": "object"},
            "zones": {"type": "array"},
            "merged_cells": {"type": "array"},
            "editable_ranges": {"type": "array"},
            "cells": {"type": "object"},
            "output_file": {"type": "string"},
        },
    },
    ("excel_toolkit", "view"): {
        "type": "object",
        "required": ["success", "file_path"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "file_path": {"type": "string"},
            "file": {"type": "string"},
            "sheet": {"type": "string"},
            "structure": {"type": "object"},
            "content": {"type": "array"},
            "row_count": {"type": "integer"},
        },
    },
    ("excel_toolkit", "merged"): {
        "type": "object",
        "required": ["success", "file_path"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "file_path": {"type": "string"},
            "file": {"type": "string"},
            "sheet": {"type": "string"},
            "merged_cells": {"type": "array"},
            "count": {"type": "integer"},
        },
    },
    ("excel_toolkit", "styles"): {
        "type": "object",
        "required": ["success", "file_path"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "file_path": {"type": "string"},
            "file": {"type": "string"},
            "sheet": {"type": "string"},
            "styles": {"type": "array"},
        },
    },
    ("excel_toolkit", "structure"): {
        "type": "object",
        "required": ["success", "file_path"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "file_path": {"type": "string"},
            "file": {"type": "string"},
            "sheet_names": {"type": "array"},
            "current_sheet": {"type": "string"},
            "structure": {"type": "object"},
            "columns": {"type": "array"},
        },
    },
    ("label_template_generator", "execute"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "image_path": {"type": "string"},
            "analysis": {"type": "object"},
            "ocr_result": {"type": "object"},
            "code": {"type": "string"},
            "output_file": {"type": "string"},
            "output_error": {"type": "string"},
        },
    },
    ("document_template", "create"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "template": {"type": "object"},
            "http_status_code": {"type": "integer"},
        },
    },
    ("document_template", "update"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "template": {"type": "object"},
            "http_status_code": {"type": "integer"},
        },
    },
    ("document_template", "delete"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "deleted": {"type": "object"},
            "http_status_code": {"type": "integer"},
        },
    },
    ("document_template", "ingest"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "ingested": {"type": "boolean"},
            "template": {"type": "object"},
            "analyzed": {"type": "object"},
            "http_status_code": {"type": "integer"},
        },
    },
    ("document_template", "upload"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "ingested": {"type": "boolean"},
            "template": {"type": "object"},
            "analyzed": {"type": "object"},
            "http_status_code": {"type": "integer"},
        },
    },
    ("template_extract", "extract"): {
        "type": "object",
        "required": ["success", "file_path", "fields", "sample_rows"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "file_path": {"type": "string"},
            "sheet_names": {"type": "array"},
            "fields": {"type": "array"},
            "sample_rows": {"type": "array"},
            "grid_preview": {"type": "object"},
            "grid_style_cache": {"type": "object"},
            "sheets": {"type": "array"},
            "artifacts": {"type": "array"},
            "error_code": {"type": "string"},
        },
    },
    ("dataset_rag", "query"): {
        "type": "object",
        "required": ["success", "dataset_id", "query", "chunks", "citations", "answer"],
        "properties": {
            "success": {"type": "boolean"},
            "dataset_id": {"type": "string"},
            "query": {"type": "string"},
            "answer": {"type": "string"},
            "chunks": {"type": "array"},
            "citations": {"type": "array"},
            "tenant_id": {"type": "string"},
            "version": {"type": "string"},
            "vector_backend_used": {"type": "boolean"},
            "index": {"type": "object"},
            "message": {"type": "string"},
            "error_code": {"type": "string"},
        },
    },
    ("dataset_rag", "ingest_document"): {
        "type": "object",
        "required": ["success", "dataset_id"],
        "properties": {
            "success": {"type": "boolean"},
            "dataset_id": {"type": "string"},
            "document": {"type": "object"},
            "chunk_count": {"type": "integer"},
            "message": {"type": "string"},
            "error_code": {"type": "string"},
        },
    },
    ("dataset_rag", "diff_versions"): {
        "type": "object",
        "required": ["success", "dataset_id"],
        "properties": {
            "success": {"type": "boolean"},
            "dataset_id": {"type": "string"},
            "source": {"type": "string"},
            "tenant_id": {"type": "string"},
            "from_document": {"type": "object"},
            "to_document": {"type": "object"},
            "from_version": {},
            "to_version": {},
            "changed": {"type": "boolean"},
            "added_lines": {"type": "array"},
            "removed_lines": {"type": "array"},
            "diff": {"type": "array"},
            "message": {"type": "string"},
            "error_code": {"type": "string"},
        },
    },
    ("dataset_rag", "rollback_version"): {
        "type": "object",
        "required": ["success", "dataset_id"],
        "properties": {
            "success": {"type": "boolean"},
            "dataset_id": {"type": "string"},
            "document": {"type": "object"},
            "chunk_count": {"type": "integer"},
            "rolled_back_from": {"type": "object"},
            "message": {"type": "string"},
            "error_code": {"type": "string"},
        },
    },
    ("dataset_rag", "rebuild_index"): {
        "type": "object",
        "required": ["success", "dataset_id"],
        "properties": {
            "success": {"type": "boolean"},
            "dataset_id": {"type": "string"},
            "job": {"type": "object"},
            "background": {"type": "boolean"},
            "message": {"type": "string"},
            "error_code": {"type": "string"},
        },
    },
    ("dataset_rag", "cancel_rebuild"): {
        "type": "object",
        "required": ["success", "dataset_id"],
        "properties": {
            "success": {"type": "boolean"},
            "dataset_id": {"type": "string"},
            "job_id": {"type": "string"},
            "job": {"type": "object"},
            "message": {"type": "string"},
            "error_code": {"type": "string"},
        },
    },
    ("dataset_rag", "delete_document"): {
        "type": "object",
        "required": ["success", "dataset_id", "document_id"],
        "properties": {
            "success": {"type": "boolean"},
            "dataset_id": {"type": "string"},
            "document_id": {"type": "string"},
            "deleted_chunks": {"type": "integer"},
            "message": {"type": "string"},
            "error_code": {"type": "string"},
        },
    },
    ("memory_v2", "propose_candidate"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "created": {"type": "boolean"},
            "candidate": {"type": "object"},
            "message": {"type": "string"},
        },
    },
    ("memory_v2", "confirm"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "memory": {"type": "object"},
            "message": {"type": "string"},
        },
    },
    ("memory_v2", "reject"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "memory": {"type": "object"},
            "message": {"type": "string"},
        },
    },
    ("memory_v2", "correct"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "memory": {"type": "object"},
            "message": {"type": "string"},
        },
    },
    ("memory_v2", "delete"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "memory": {"type": "object"},
            "message": {"type": "string"},
        },
    },
}
