from __future__ import annotations

from typing import Any

_DEFAULT_OUTPUT_SCHEMA: dict[str, Any] = {
    "type": "object",
    "required": ["success"],
    "properties": {
        "success": {"type": "boolean"},
        "message": {"type": "string"},
        "data": {},
    },
}

_SPECIAL_OUTPUT_SCHEMAS: dict[tuple[str, str], dict[str, Any]] = {
    ("business_db", "read"): {
        "type": "object",
        "required": ["success", "data"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "data": {"type": "array"},
            "error": {"type": "string"},
        },
    },
    ("business_db", "write"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "data": {"type": "object"},
            "error": {"type": "string"},
        },
    },
    ("customers", "create"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "created": {"type": "boolean"},
            "data": {"type": "object"},
            "raw": {"type": "object"},
            "error": {"type": "string"},
        },
    },
    ("customers", "update"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "data": {"type": "object"},
            "error": {"type": "string"},
        },
    },
    ("customers", "delete"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "deleted_count": {"type": "integer"},
            "data": {"type": "object"},
            "error": {"type": "string"},
        },
    },
    ("customers", "batch_delete"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "deleted": {"type": "integer"},
            "deleted_count": {"type": "integer"},
            "skipped": {"type": "array"},
            "data": {"type": "object"},
            "error": {"type": "string"},
        },
    },
    ("products", "create"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "created": {"type": "boolean"},
            "raw": {"type": "object"},
            "data": {"type": "object"},
            "error": {"type": "string"},
        },
    },
    ("products", "update"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "data": {"type": "object"},
            "error": {"type": "string"},
        },
    },
    ("products", "delete"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "data": {"type": "object"},
            "error": {"type": "string"},
        },
    },
    ("products", "batch_create"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "data": {"type": "object"},
            "error": {"type": "string"},
        },
    },
    ("products", "batch_delete"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "deleted": {"type": "integer"},
            "deleted_count": {"type": "integer"},
            "skipped": {"type": "array"},
            "data": {"type": "object"},
            "status_code": {"type": "integer"},
            "error_code": {"type": "string"},
            "error": {"type": "string"},
        },
    },
    ("materials", "create"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "data": {"type": "object"},
            "created": {"type": "boolean"},
            "error": {"type": "string"},
        },
    },
    ("materials", "update"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "data": {"type": "object"},
            "error": {"type": "string"},
        },
    },
    ("materials", "delete"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "data": {"type": "object"},
            "deleted_count": {"type": "integer"},
            "error": {"type": "string"},
        },
    },
    ("materials", "batch_delete"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "deleted_count": {"type": "integer"},
            "data": {"type": "object"},
            "warning": {"type": "string"},
            "error": {"type": "string"},
        },
    },
    ("inventory", "create_storage_location"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "id": {"type": "integer"},
            "data": {"type": "object"},
            "error": {"type": "string"},
        },
    },
    ("inventory", "update_storage_location"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "data": {"type": "object"},
            "error": {"type": "string"},
        },
    },
    ("inventory", "create_warehouse"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "id": {"type": "integer"},
            "data": {"type": "object"},
            "error": {"type": "string"},
        },
    },
    ("inventory", "update_warehouse"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "data": {"type": "object"},
            "error": {"type": "string"},
        },
    },
    ("inventory", "delete_warehouse"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "data": {"type": "object"},
            "error": {"type": "string"},
        },
    },
    ("inventory", "stock_in"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "data": {"type": "object"},
            "error": {"type": "string"},
        },
    },
    ("inventory", "stock_out"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "data": {"type": "object"},
            "error": {"type": "string"},
        },
    },
    ("inventory", "transfer"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "data": {"type": "object"},
            "error": {"type": "string"},
        },
    },
    ("purchase", "create_supplier"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "data": {"type": "object"},
            "error": {"type": "string"},
        },
    },
    ("purchase", "update_supplier"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "data": {"type": "object"},
            "error": {"type": "string"},
        },
    },
    ("purchase", "delete_supplier"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "data": {"type": "object"},
            "error": {"type": "string"},
        },
    },
    ("purchase", "create_order"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "data": {"type": "object"},
            "error": {"type": "string"},
        },
    },
    ("purchase", "update_order"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "data": {"type": "object"},
            "error": {"type": "string"},
        },
    },
    ("purchase", "approve_order"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "data": {"type": "object"},
            "error": {"type": "string"},
        },
    },
    ("purchase", "cancel_order"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "data": {"type": "object"},
            "error": {"type": "string"},
        },
    },
    ("purchase", "create_inbound"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "data": {"type": "object"},
            "error": {"type": "string"},
        },
    },
    ("finance", "create_transaction"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "data": {"type": "object"},
            "error": {"type": "string"},
        },
    },
    ("finance", "update_transaction"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "data": {"type": "object"},
            "error": {"type": "string"},
        },
    },
    ("finance", "delete_transaction"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "data": {"type": "object"},
            "error": {"type": "string"},
        },
    },
    ("employee", "list"): {
        "type": "object",
        "required": ["success", "data"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "data": {"type": "array"},
        },
    },
    ("employee", "execute"): {
        "type": "object",
        "required": ["success", "message", "data"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "data": {"type": "object"},
            "employee_id": {"type": "string"},
        },
    },
    ("excel_import", "execute_import"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "imported_count": {"type": "integer"},
            "data": {"type": "object"},
        },
    },
    ("excel_import", "import_records"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "imported_count": {"type": "integer"},
            "data": {"type": "object"},
        },
    },
    ("unit_products_import", "execute_import"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "created_customers": {"type": "integer"},
            "created_products": {"type": "integer"},
            "data": {"type": "object"},
        },
    },
    ("generate_office_document", "execute"): {
        "type": "object",
        "required": ["success", "file_name", "download_url", "artifacts"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "file_name": {"type": "string"},
            "download_url": {"type": "string"},
            "pickup_token": {"type": "string"},
            "artifacts": {"type": "array"},
        },
    },
    ("excel_vector_index", "execute"): {
        "type": "object",
        "required": ["success", "index_id"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "index_id": {"type": "string"},
            "excel_vector_index_id": {"type": "string"},
            "excel_index_id": {"type": "string"},
            "chunk_count": {"type": "integer"},
            "row_count": {"type": "integer"},
            "error": {"type": "string"},
        },
    },
    ("excel_vector_index", "query"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "index_id": {"type": "string"},
            "query": {"type": "string"},
            "hits": {"type": "array"},
            "error": {"type": "string"},
        },
    },
    ("ocr", "recognize"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "text": {"type": "string"},
            "file_path": {"type": "string"},
            "confidence": {"type": "number"},
            "artifacts": {"type": "array"},
            "error_code": {"type": "string"},
        },
    },
    ("ocr", "request"): {
        "type": "object",
        "required": ["success", "request_id", "event", "published"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "request_id": {"type": "string"},
            "image_url": {"type": "string"},
            "ocr_type": {"type": "string"},
            "user_id": {"type": "string"},
            "event": {"type": "string"},
            "published": {"type": "boolean"},
            "error_code": {"type": "string"},
        },
    },
    ("ocr", "extract"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "data": {"type": "object"},
            "error_code": {"type": "string"},
        },
    },
    ("ocr", "analyze"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "data": {"type": "object"},
            "error_code": {"type": "string"},
        },
    },
    ("ocr", "recognize_and_extract"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "text": {"type": "string"},
            "data": {"type": "object"},
            "analysis": {"type": "object"},
            "artifacts": {"type": "array"},
            "error_code": {"type": "string"},
        },
    },
    ("shipment_records", "create"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "data": {"type": "object"},
            "record_id": {"type": "integer"},
            "order_id": {"type": "integer"},
            "error": {"type": "string"},
        },
    },
    ("shipment_records", "update"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "data": {"type": "object"},
            "error": {"type": "string"},
        },
    },
    ("shipment_records", "delete"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "deleted_count": {"type": "integer"},
            "data": {"type": "object"},
            "error": {"type": "string"},
        },
    },
    ("shipment_orders", "generate"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "file_path": {"type": "string"},
            "doc_name": {"type": "string"},
            "record_id": {"type": "integer"},
            "order_id": {"type": "integer"},
            "data": {"type": "object"},
            "error": {"type": "string"},
        },
    },
    ("shipment_orders", "generate_batch"): {
        "type": "object",
        "required": ["success", "data"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "data": {"type": "object"},
            "error": {"type": "string"},
        },
    },
    ("shipment_orders", "print"): {
        "type": "object",
        "required": ["success", "file_path", "updated"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "file_path": {"type": "string"},
            "updated": {"type": "boolean"},
            "printed_at": {"type": "string"},
            "warning": {"type": "string"},
            "error": {"type": "string"},
        },
    },
    ("shipment_orders", "clear_shipment"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "purchase_unit": {"type": "string"},
            "cleared_count": {"type": "integer"},
            "deleted_count": {"type": "integer"},
            "data": {"type": "object"},
            "error": {"type": "string"},
        },
    },
    ("shipment_orders", "set_sequence"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "sequence": {"type": "integer"},
            "data": {"type": "object"},
            "error": {"type": "string"},
        },
    },
    ("shipment_orders", "reset_sequence"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "sequence": {"type": "integer"},
            "data": {"type": "object"},
            "error": {"type": "string"},
        },
    },
    ("shipment_orders", "clear_all"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "cleared_count": {"type": "integer"},
            "deleted_count": {"type": "integer"},
            "data": {"type": "object"},
            "error": {"type": "string"},
        },
    },
    ("shipment_orders", "delete"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "deleted_id": {"type": "integer"},
            "deleted_count": {"type": "integer"},
            "data": {"type": "object"},
            "error": {"type": "string"},
        },
    },
    ("print", "print_document"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "file_path": {"type": "string"},
            "printer": {},
            "printer_name": {"type": "string"},
            "status": {"type": "string"},
            "job_id": {"type": "string"},
            "error_code": {"type": "string"},
            "error": {"type": "string"},
        },
    },
    ("print", "print_label"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "file_path": {"type": "string"},
            "printer": {},
            "printer_name": {"type": "string"},
            "copies": {"type": "integer"},
            "status": {"type": "string"},
            "require_confirm": {"type": "boolean"},
            "job_id": {"type": "string"},
            "error_code": {"type": "string"},
            "error": {"type": "string"},
        },
    },
    ("print", "test"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "printer_name": {"type": "string"},
            "status": {"type": "string"},
            "error_code": {"type": "string"},
            "error": {"type": "string"},
        },
    },
    ("print", "save_printer_selection"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "selection": {"type": "object"},
            "document_printer": {"type": "string"},
            "label_printer": {"type": "string"},
            "document": {},
            "label": {},
            "error_code": {"type": "string"},
            "error": {"type": "string"},
        },
    },
    ("print", "workflow_label_dispatch"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "model_number": {"type": "string"},
            "product_name": {"type": "string"},
            "quantity": {"type": "integer"},
            "file_path": {"type": "string"},
            "status": {"type": "string"},
            "job_id": {"type": "string"},
            "error_code": {"type": "string"},
            "error": {"type": "string"},
        },
    },
    ("business_event", "print_label"): {
        "type": "object",
        "required": ["success", "job_id", "event"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "job_id": {"type": "string"},
            "event": {"type": "string"},
        },
    },
    ("business_event", "inventory_update"): {
        "type": "object",
        "required": ["success", "event"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "event": {"type": "string"},
        },
    },
    ("business_event", "shipment_create"): {
        "type": "object",
        "required": ["success", "event", "published"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "event": {"type": "string"},
            "published": {"type": "boolean"},
        },
    },
    ("system_maintenance", "set_default_printer"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "data": {"type": "object"},
            "http_status_code": {"type": "integer"},
        },
    },
    ("system_maintenance", "enable_startup"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "data": {"type": "object"},
            "http_status_code": {"type": "integer"},
        },
    },
    ("system_maintenance", "disable_startup"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "data": {"type": "object"},
            "http_status_code": {"type": "integer"},
        },
    },
    ("system_maintenance", "backup_database"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "backup_file": {"type": "string"},
            "data": {"type": "object"},
            "http_status_code": {"type": "integer"},
        },
    },
    ("system_maintenance", "delete_database_backup"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "backup_file": {"type": "string"},
            "http_status_code": {"type": "integer"},
        },
    },
    ("system_maintenance", "restore_database"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "backup_file": {"type": "string"},
            "http_status_code": {"type": "integer"},
        },
    },
    ("system_maintenance", "clear_performance_cache"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "http_status_code": {"type": "integer"},
        },
    },
    ("system_maintenance", "invalidate_performance_cache"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "data": {"type": "object"},
            "http_status_code": {"type": "integer"},
        },
    },
    ("system_maintenance", "reinitialize_performance"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "data": {"type": "object"},
            "http_status_code": {"type": "integer"},
        },
    },
    ("excel_analysis", "read"): {
        "type": "object",
        "required": ["success", "data"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "data": {"type": "object"},
        },
    },
    ("excel_analysis", "query"): {
        "type": "object",
        "required": ["success", "data"],
        "properties": {
            "success": {"type": "boolean"},
            "answer": {"type": "string"},
            "data": {"type": "object"},
        },
    },
    ("excel_analyzer", "analyze"): {
        "type": "object",
        "required": ["success", "file_path"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "file_path": {"type": "string"},
            "file": {"type": "string"},
            "sheet": {"type": "string"},
            "structure": {"type": "object"},
            "zones": {"type": "array"},
            "merged_cells": {"type": "array"},
            "editable_ranges": {"type": "array"},
            "cells": {"type": "object"},
            "output_file": {"type": "string"},
        },
    },
    ("excel_toolkit", "view"): {
        "type": "object",
        "required": ["success", "file_path"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "file_path": {"type": "string"},
            "file": {"type": "string"},
            "sheet": {"type": "string"},
            "structure": {"type": "object"},
            "content": {"type": "array"},
            "row_count": {"type": "integer"},
        },
    },
    ("excel_toolkit", "merged"): {
        "type": "object",
        "required": ["success", "file_path"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "file_path": {"type": "string"},
            "file": {"type": "string"},
            "sheet": {"type": "string"},
            "merged_cells": {"type": "array"},
            "count": {"type": "integer"},
        },
    },
    ("excel_toolkit", "styles"): {
        "type": "object",
        "required": ["success", "file_path"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "file_path": {"type": "string"},
            "file": {"type": "string"},
            "sheet": {"type": "string"},
            "styles": {"type": "array"},
        },
    },
    ("excel_toolkit", "structure"): {
        "type": "object",
        "required": ["success", "file_path"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "file_path": {"type": "string"},
            "file": {"type": "string"},
            "sheet_names": {"type": "array"},
            "current_sheet": {"type": "string"},
            "structure": {"type": "object"},
            "columns": {"type": "array"},
        },
    },
    ("label_template_generator", "execute"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "image_path": {"type": "string"},
            "analysis": {"type": "object"},
            "ocr_result": {"type": "object"},
            "code": {"type": "string"},
            "output_file": {"type": "string"},
            "output_error": {"type": "string"},
        },
    },
    ("document_template", "create"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "template": {"type": "object"},
            "http_status_code": {"type": "integer"},
        },
    },
    ("document_template", "update"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "template": {"type": "object"},
            "http_status_code": {"type": "integer"},
        },
    },
    ("document_template", "delete"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "deleted": {"type": "object"},
            "http_status_code": {"type": "integer"},
        },
    },
    ("template_extract", "extract"): {
        "type": "object",
        "required": ["success", "file_path", "fields", "sample_rows"],
        "properties": {
            "success": {"type": "boolean"},
            "message": {"type": "string"},
            "file_path": {"type": "string"},
            "sheet_names": {"type": "array"},
            "fields": {"type": "array"},
            "sample_rows": {"type": "array"},
            "grid_preview": {"type": "object"},
            "grid_style_cache": {"type": "object"},
            "sheets": {"type": "array"},
            "artifacts": {"type": "array"},
            "error_code": {"type": "string"},
        },
    },
    ("dataset_rag", "query"): {
        "type": "object",
        "required": ["success", "dataset_id", "query", "chunks", "citations", "answer"],
        "properties": {
            "success": {"type": "boolean"},
            "dataset_id": {"type": "string"},
            "query": {"type": "string"},
            "answer": {"type": "string"},
            "chunks": {"type": "array"},
            "citations": {"type": "array"},
            "tenant_id": {"type": "string"},
            "version": {"type": "string"},
            "vector_backend_used": {"type": "boolean"},
            "index": {"type": "object"},
            "message": {"type": "string"},
            "error_code": {"type": "string"},
        },
    },
    ("dataset_rag", "ingest_document"): {
        "type": "object",
        "required": ["success", "dataset_id"],
        "properties": {
            "success": {"type": "boolean"},
            "dataset_id": {"type": "string"},
            "document": {"type": "object"},
            "chunk_count": {"type": "integer"},
            "message": {"type": "string"},
            "error_code": {"type": "string"},
        },
    },
    ("dataset_rag", "diff_versions"): {
        "type": "object",
        "required": ["success", "dataset_id"],
        "properties": {
            "success": {"type": "boolean"},
            "dataset_id": {"type": "string"},
            "source": {"type": "string"},
            "tenant_id": {"type": "string"},
            "from_document": {"type": "object"},
            "to_document": {"type": "object"},
            "from_version": {},
            "to_version": {},
            "changed": {"type": "boolean"},
            "added_lines": {"type": "array"},
            "removed_lines": {"type": "array"},
            "diff": {"type": "array"},
            "message": {"type": "string"},
            "error_code": {"type": "string"},
        },
    },
    ("dataset_rag", "rollback_version"): {
        "type": "object",
        "required": ["success", "dataset_id"],
        "properties": {
            "success": {"type": "boolean"},
            "dataset_id": {"type": "string"},
            "document": {"type": "object"},
            "chunk_count": {"type": "integer"},
            "rolled_back_from": {"type": "object"},
            "message": {"type": "string"},
            "error_code": {"type": "string"},
        },
    },
    ("dataset_rag", "rebuild_index"): {
        "type": "object",
        "required": ["success", "dataset_id"],
        "properties": {
            "success": {"type": "boolean"},
            "dataset_id": {"type": "string"},
            "job": {"type": "object"},
            "background": {"type": "boolean"},
            "message": {"type": "string"},
            "error_code": {"type": "string"},
        },
    },
    ("dataset_rag", "cancel_rebuild"): {
        "type": "object",
        "required": ["success", "dataset_id"],
        "properties": {
            "success": {"type": "boolean"},
            "dataset_id": {"type": "string"},
            "job_id": {"type": "string"},
            "job": {"type": "object"},
            "message": {"type": "string"},
            "error_code": {"type": "string"},
        },
    },
    ("dataset_rag", "delete_document"): {
        "type": "object",
        "required": ["success", "dataset_id", "document_id"],
        "properties": {
            "success": {"type": "boolean"},
            "dataset_id": {"type": "string"},
            "document_id": {"type": "string"},
            "deleted_chunks": {"type": "integer"},
            "message": {"type": "string"},
            "error_code": {"type": "string"},
        },
    },
    ("memory_v2", "propose_candidate"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "created": {"type": "boolean"},
            "candidate": {"type": "object"},
            "message": {"type": "string"},
        },
    },
    ("memory_v2", "confirm"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "memory": {"type": "object"},
            "message": {"type": "string"},
        },
    },
    ("memory_v2", "reject"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "memory": {"type": "object"},
            "message": {"type": "string"},
        },
    },
    ("memory_v2", "correct"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "memory": {"type": "object"},
            "message": {"type": "string"},
        },
    },
    ("memory_v2", "delete"): {
        "type": "object",
        "required": ["success"],
        "properties": {
            "success": {"type": "boolean"},
            "memory": {"type": "object"},
            "message": {"type": "string"},
        },
    },
}
