"""Static registry data extracted from the public facade."""

from __future__ import annotations

EMPLOYEE_TOOLS: dict[str, list[str]] = {
    "site-content-editor": ["read_file", "list_docs", "git_status", "git_diff"],
    "seo-sitemap-curator": ["read_file", "list_docs", "api_health", "git_status"],
    "marketing-site-builder": ["list_docs", "read_file", "list_scripts", "git_status"],
    "flask-entry-keeper": ["read_file", "api_health", "git_diff", "run_ruff_check"],
    "market-frontend-dev": ["frontend_lint", "frontend_typecheck", "frontend_test", "git_diff"],
    "workbench-ux-stylist": ["frontend_lint", "frontend_test", "read_file", "list_docs"],
    "user-customer-service-officer": [
        "list_employees",
        "employee_status",
        "list_action_items",
        "list_users",
    ],
    "intake-dispatcher": ["list_employees", "list_workbench_sessions", "list_action_items"],
    "fhd-core-maintainer": [
        "run_pytest",
        "run_ruff_check",
        "run_mypy",
        "check_coverage",
        "count_type_debt",
        "count_raw_sql",
        "verify_version_anchors",
        "git_diff",
        "patch_file",
        "write_file",
    ],
    "vibe-coding-maintainer": [
        "run_pytest",
        "run_ruff_check",
        "git_status",
        "git_diff",
        "read_file",
    ],
    "mods-and-eskill-curator": [
        "list_mods",
        "list_employee_packs",
        "validate_employee_pack",
        "mod_loading_status",
    ],
    "change-request-auditor": [
        "git_diff",
        "git_log",
        "run_ruff_check",
        "run_mypy",
        "verify_employee_contract",
    ],
    "daily-orchestrator": [
        "list_employees",
        "employee_status",
        "duty_graph_health",
        "list_action_items",
        "employee_autonomy_dashboard",
    ],
    "task-router-officer": ["list_employees", "employee_status", "list_action_items"],
    "enterprise-adoption-officer": ["list_users", "list_enterprise_mods", "list_mods"],
    "delivery-receipt-officer": ["git_log", "git_status", "list_action_items", "api_health"],
    "mobile-android-release-officer": [
        "android_gradle_build",
        "git_status",
        "git_log",
        "list_scripts",
    ],
    "mobile-ios-release-officer": ["git_status", "git_log", "list_scripts", "read_file"],
    "modstore-backend-api": [
        "api_health",
        "run_pytest",
        "run_ruff_check",
        "git_diff",
        "performance_status",
    ],
    "employee-pack-curator": [
        "list_employee_packs",
        "validate_employee_pack",
        "list_mods",
        "verify_employee_contract",
    ],
    "java-payment-bridge-officer": [
        "api_health",
        "check_transactions",
        "list_invoices",
        "read_file",
    ],
    "payment-billing-reconciler": [
        "check_transactions",
        "list_invoices",
        "list_users",
        "read_file",
    ],
    "nginx-config-engineer": ["nginx_test", "api_health", "read_file", "git_diff"],
    "push-update-context-officer": ["list_deploy_scripts", "git_log", "api_health", "read_file"],
    "deploy-release-officer": [
        "pack_release",
        "list_deploy_scripts",
        "trigger_gh_workflow",
        "git_status",
        "git_log",
        "api_health",
    ],
    "security-secrets-guard": ["git_diff", "read_file", "list_scripts", "git_status"],
    "log-monitor-incident": ["tail_logs", "api_health", "performance_status", "disk_usage"],
    "retention-officer": ["disk_usage", "tail_logs", "list_scripts", "git_status"],
    "dbops-engineer": ["api_health", "performance_status", "read_file", "tail_logs"],
    "legacy-archive-curator": ["disk_usage", "list_scripts", "git_status", "read_file"],
    "llm-ops-engineer": [
        "read_llm_env_config",
        "list_configured_providers",
        "test_llm_key_health",
        "query_provider_usage",
        "compare_model_prices",
        "list_vlm_models",
        "get_vlm_route",
        "query_local_token_usage",
        "query_cursor_usage",
        "query_codex_usage",
        "query_trae_usage",
    ],
    "test-qa-runner": [
        "run_pytest",
        "run_ruff_check",
        "run_ruff_format",
        "run_mypy",
        "check_coverage",
        "run_arch_fitness",
        "frontend_test",
    ],
    "doc-knowledge-curator": ["list_docs", "read_file", "verify_version_anchors", "git_status"],
    "employee-interview-assistant": [
        "list_employees",
        "list_employee_packs",
        "validate_employee_pack",
        "employee_status",
    ],
    "employee-pack-quality-interviewer": [
        "validate_employee_pack",
        "list_employee_packs",
        "verify_employee_contract",
        "list_mods",
    ],
    "intent-analyst": ["list_workbench_sessions", "list_employees", "list_action_items"],
    "employee-planner": ["list_employees", "list_workbench_sessions", "read_file", "list_docs"],
    "artifact-generator": ["sandbox_python", "read_file", "list_scripts", "git_diff"],
    "quality-validator": [
        "run_ruff_check",
        "run_mypy",
        "run_arch_fitness",
        "verify_employee_contract",
    ],
    "miniapp-builder": ["frontend_lint", "frontend_typecheck", "list_scripts", "read_file"],
    "script-binder": ["read_file", "list_scripts", "sandbox_python", "git_diff"],
    "workflow-automator": ["list_scripts", "read_file", "api_health", "list_action_items"],
    "pack-registrar": ["list_employee_packs", "validate_employee_pack", "list_mods", "git_status"],
    "sandbox-tester": ["sandbox_python", "run_pytest", "frontend_test", "read_file"],
    "code-validator": ["run_ruff_check", "run_ruff_format", "run_mypy", "run_arch_fitness"],
    "self-checker": ["run_pytest", "run_ruff_check", "verify_version_anchors", "check_coverage"],
    "host-checker": [
        "api_health",
        "disk_usage",
        "nginx_test",
        "mod_loading_status",
        "performance_status",
    ],
    "hex-quality-assessor": [
        "run_pytest",
        "run_ruff_check",
        "run_mypy",
        "check_coverage",
        "count_type_debt",
        "count_raw_sql",
        "run_arch_fitness",
        "mutation_kill_report",
    ],
    "ecosystem-partner-onboard-officer": [
        "list_users",
        "list_enterprise_mods",
        "list_mods",
        "list_action_items",
    ],
    "ecosystem-joint-catalog-officer": [
        "list_mods",
        "list_enterprise_mods",
        "list_employee_packs",
        "validate_employee_pack",
    ],
    "ecosystem-delivery-reporter": ["git_log", "list_action_items", "api_health", "list_employees"],
    "ecosystem-investor-portal-officer": [
        "list_users",
        "list_invoices",
        "check_transactions",
        "api_health",
    ],
    "ecosystem-revenue-share-reconciler": [
        "check_transactions",
        "list_invoices",
        "list_users",
        "read_file",
    ],
}
