"""Static registry data extracted from the public facade."""

from __future__ import annotations

from typing import Any

_PROVIDER_PROFILES: list[dict[str, Any]] = [
    {
        "name": "b.ai",
        "env_keys": ["OPENAI_API_KEY"],
        "base_url_env": "OPENAI_BASE_URL",
        "base_url_default": "https://api.b.ai/v1",
        "model_env": "OPENAI_MODEL",
        "default_model": "MiniMax-M3",
        "ping_model": "MiniMax-M3",
        "billing_endpoints": [
            "/dashboard/billing/credit_grants",
            "/dashboard/billing/subscription",
        ],
        "detect": lambda env: "b.ai" in env.get("OPENAI_BASE_URL", ""),
    },
    {
        "name": "openai",
        "env_keys": ["OPENAI_API_KEY"],
        "base_url_env": "OPENAI_BASE_URL",
        "base_url_default": "https://api.openai.com/v1",
        "model_env": "OPENAI_MODEL",
        "default_model": "gpt-4o-mini",
        "ping_model": "gpt-4o-mini",
        "billing_endpoints": ["/dashboard/billing/credit_grants"],
        "detect": lambda env: env.get("OPENAI_BASE_URL", "") in ("", "https://api.openai.com/v1"),
    },
    {
        "name": "deepseek",
        "env_keys": ["DEEPSEEK_API_KEY"],
        "base_url_env": "DEEPSEEK_BASE_URL",
        "base_url_default": "https://api.deepseek.com/v1",
        "model_env": "DEEPSEEK_MODEL",
        "default_model": "deepseek-chat",
        "ping_model": "deepseek-chat",
        "billing_endpoints": ["/user/balance"],
    },
    {
        "name": "qwen",
        "env_keys": ["DASHSCOPE_API_KEY", "QWEN_API_KEY"],
        "base_url_env": "DASHSCOPE_BASE_URL",
        "base_url_default": "https://dashscope.aliyuncs.com/compatible-mode/v1",
        "model_env": "QWEN_MODEL",
        "default_model": "qwen-plus",
        "ping_model": "qwen-turbo",
        "billing_endpoints": [],
    },
    {
        "name": "zhipu",
        "env_keys": ["ZHIPU_API_KEY", "GLM_API_KEY"],
        "base_url_env": "ZHIPU_BASE_URL",
        "base_url_default": "https://open.bigmodel.cn/api/paas/v4",
        "model_env": "GLM_MODEL",
        "default_model": "glm-4-plus",
        "ping_model": "glm-4-flash",
        "billing_endpoints": [],
    },
    {
        "name": "moonshot",
        "env_keys": ["MOONSHOT_API_KEY", "KIMI_API_KEY"],
        "base_url_env": "MOONSHOT_BASE_URL",
        "base_url_default": "https://api.moonshot.cn/v1",
        "model_env": "MOONSHOT_MODEL",
        "default_model": "moonshot-v1-8k",
        "ping_model": "moonshot-v1-8k",
        "billing_endpoints": ["/users/me/balance"],
    },
    {
        "name": "siliconflow",
        "env_keys": ["SILICONFLOW_API_KEY"],
        "base_url_env": "SILICONFLOW_BASE_URL",
        "base_url_default": "https://api.siliconflow.cn/v1",
        "model_env": "SILICONFLOW_MODEL",
        "default_model": "deepseek-ai/DeepSeek-V3",
        "ping_model": "Qwen/Qwen2.5-7B-Instruct",
        "billing_endpoints": ["/user/info"],
    },
    {
        "name": "openrouter",
        "env_keys": ["OPENROUTER_API_KEY"],
        "base_url_env": "OPENROUTER_BASE_URL",
        "base_url_default": "https://openrouter.ai/api/v1",
        "model_env": "OPENROUTER_MODEL",
        "default_model": "openai/gpt-4o-mini",
        "ping_model": "openai/gpt-4o-mini",
        "billing_endpoints": ["/credits"],
    },
    {
        "name": "volcengine",
        "env_keys": ["VOLC_API_KEY", "ARK_API_KEY"],
        "base_url_env": "VOLC_BASE_URL",
        "base_url_default": "https://ark.cn-beijing.volces.com/api/v3",
        "model_env": "VOLC_MODEL",
        "default_model": "doubao-pro-32k",
        "ping_model": "doubao-lite-4k",
        "billing_endpoints": [],
    },
    {
        "name": "ollama",
        "env_keys": [],
        "base_url_env": "OLLAMA_BASE_URL",
        "base_url_default": "http://localhost:11434/v1",
        "model_env": "OLLAMA_MODEL",
        "default_model": "llama3.2",
        "ping_model": "llama3.2",
        "billing_endpoints": ["/api/tags"],
        "no_auth": True,
    },
    {
        "name": "minimax",
        "env_keys": [
            "MINIMAX_TOKEN_PLAN_API_KEY",
            "MINIMAX_CODING_PLAN_API_KEY",
            "MINIMAX_API_KEY",
        ],
        "base_url_env": "MINIMAX_BASE_URL",
        "base_url_default": "https://api.minimaxi.com",
        "model_env": "MINIMAX_MODEL",
        "default_model": "MiniMax-M2.7",
        "ping_model": "MiniMax-M2.7",
        "billing_endpoints": ["https://www.minimaxi.com/v1/token_plan/remains"],
    },
    {
        "name": "mimo",
        "env_keys": ["MIMO_API_KEY", "XIAOMI_API_KEY", "XIAOMI_MIMO_API_KEY"],
        "base_url_env": "MIMO_BASE_URL",
        "base_url_default": "https://token-plan-cn.xiaomimimo.com/v1",
        "model_env": "MIMO_MODEL",
        "default_model": "mimo-v2.5-pro",
        "ping_model": "mimo-v2.5-pro",
        "billing_endpoints": [],
    },
]

_LLM_ENV_KEYS: tuple[str, ...] = tuple(
    dict.fromkeys(
        [k for p in _PROVIDER_PROFILES for k in p["env_keys"]]
        + [p["base_url_env"] for p in _PROVIDER_PROFILES if p.get("base_url_env")]
        + [p["model_env"] for p in _PROVIDER_PROFILES if p.get("model_env")]
        + [
            "XCAGI_LLM_PROVIDER",
            "LLM_PROVIDER",
            "LLM_MODE",
            "FHD_LLM_MODE",
            "XCAUTO_API_KEY",
            "XCAUTO_PAT",
            "XIUCI_API_KEY",
            "XCAGI_EMPLOYEE_LLM_MODEL",
            "XCAGI_EMPLOYEE_VLM_MODEL",
            "XCAGI_EMPLOYEE_VLM_PROVIDER",
            "FHD_TEMPLATE_VLM_ENRICH",
        ]
    )
)

_MODEL_PRICES: list[dict[str, Any]] = [
    {
        "model": "DeepSeek-V3",
        "provider": "DeepSeek",
        "input_per_1m": 0.27,
        "output_per_1m": 1.1,
        "context": "64K",
        "note": "国产最便宜之一",
    },
    {
        "model": "DeepSeek-R1",
        "provider": "DeepSeek",
        "input_per_1m": 0.55,
        "output_per_1m": 2.19,
        "context": "64K",
        "note": "推理模型",
    },
    {
        "model": "MiniMax-M3",
        "provider": "b.ai",
        "input_per_1m": 0.4,
        "output_per_1m": 1.5,
        "context": "1M",
        "note": "当前在用",
    },
    {
        "model": "MiniMax-Text-01",
        "provider": "MiniMax",
        "input_per_1m": 0.2,
        "output_per_1m": 0.8,
        "context": "1M",
        "note": "便宜",
    },
    {
        "model": "gpt-4o",
        "provider": "OpenAI",
        "input_per_1m": 2.5,
        "output_per_1m": 10.0,
        "context": "128K",
        "note": "贵",
    },
    {
        "model": "gpt-4o-mini",
        "provider": "OpenAI",
        "input_per_1m": 0.15,
        "output_per_1m": 0.6,
        "context": "128K",
        "note": "性价比高",
    },
    {
        "model": "claude-3.5-sonnet",
        "provider": "Anthropic",
        "input_per_1m": 3.0,
        "output_per_1m": 15.0,
        "context": "200K",
        "note": "最贵",
    },
    {
        "model": "qwen-max",
        "provider": "qwen",
        "input_per_1m": 1.4,
        "output_per_1m": 5.6,
        "context": "32K",
        "note": "",
    },
    {
        "model": "qwen-plus",
        "provider": "qwen",
        "input_per_1m": 0.14,
        "output_per_1m": 0.56,
        "context": "128K",
        "note": "便宜",
    },
    {
        "model": "qwen-turbo",
        "provider": "qwen",
        "input_per_1m": 0.05,
        "output_per_1m": 0.2,
        "context": "1M",
        "note": "最便宜之一",
    },
    {
        "model": "glm-4-plus",
        "provider": "zhipu",
        "input_per_1m": 0.7,
        "output_per_1m": 0.7,
        "context": "128K",
        "note": "",
    },
    {
        "model": "glm-4-flash",
        "provider": "zhipu",
        "input_per_1m": 0.0,
        "output_per_1m": 0.0,
        "context": "128K",
        "note": "免费！",
    },
    {
        "model": "moonshot-v1-8k",
        "provider": "moonshot",
        "input_per_1m": 1.68,
        "output_per_1m": 1.68,
        "context": "8K",
        "note": "",
    },
    {
        "model": "moonshot-v1-32k",
        "provider": "moonshot",
        "input_per_1m": 3.36,
        "output_per_1m": 3.36,
        "context": "32K",
        "note": "",
    },
    {
        "model": "deepseek-ai/DeepSeek-V3",
        "provider": "siliconflow",
        "input_per_1m": 0.27,
        "output_per_1m": 1.1,
        "context": "64K",
        "note": "聚合代理",
    },
    {
        "model": "Qwen/Qwen2.5-7B-Instruct",
        "provider": "siliconflow",
        "input_per_1m": 0.0,
        "output_per_1m": 0.0,
        "context": "32K",
        "note": "免费！",
    },
    {
        "model": "openai/gpt-4o-mini",
        "provider": "openrouter",
        "input_per_1m": 0.15,
        "output_per_1m": 0.6,
        "context": "128K",
        "note": "聚合代理",
    },
    {
        "model": "doubao-pro-32k",
        "provider": "volcengine",
        "input_per_1m": 0.11,
        "output_per_1m": 0.28,
        "context": "32K",
        "note": "便宜",
    },
    {
        "model": "doubao-lite-4k",
        "provider": "volcengine",
        "input_per_1m": 0.003,
        "output_per_1m": 0.007,
        "context": "4K",
        "note": "极便宜",
    },
    {
        "model": "llama3.2",
        "provider": "ollama",
        "input_per_1m": 0.0,
        "output_per_1m": 0.0,
        "context": "128K",
        "note": "本地免费！",
    },
    {
        "model": "qwen2.5:7b",
        "provider": "ollama",
        "input_per_1m": 0.0,
        "output_per_1m": 0.0,
        "context": "32K",
        "note": "本地免费！",
    },
    {
        "model": "mimo-v2.5-pro",
        "provider": "mimo",
        "input_per_1m": 0.0,
        "output_per_1m": 0.0,
        "context": "128K",
        "note": "Token Plan 订阅期内免费",
    },
]
