global:
  namespace: xcagi-staging

api:
  image: xcagi/fhd-api:10.0.0
  replicas: 1
  service:
    type: NodePort
    nodePort: 30080
  envFrom: []

monitoring:
  enabled: true
  prometheus:
    image: prom/prometheus:v2.53.0
    retention: 8d
    pvcSize: 15Gi
    nodePort: 30090
  grafana:
    image: grafana/grafana:11.0.0
    nodePort: 30300
  loki:
    image: grafana/loki:3.0.0
    pvcSize: 10Gi
  promtail:
    image: grafana/promtail:3.0.0
  k6:
    enabled: false
    image: grafana/k6:0.54.0
    duration: 168h

storageClassName: local-path
