{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: xcagi-network-policy
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "xcagi-fhd-api.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "xcagi-fhd-api.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector: {}
    {{- range $ns := .Values.networkPolicy.allowNamespaces }}
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ $ns }}
    {{- end }}
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - {}
{{- end }}
