{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: {{ include "xcagi.namespace" . }}
  labels:
    {{- include "xcagi.labels" . | nindent 4 }}
    app: redis
spec:
  ports:
    - port: {{ .Values.redis.port }}
      targetPort: {{ .Values.redis.port }}
  selector:
    app: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: {{ include "xcagi.namespace" . }}
  labels:
    {{- include "xcagi.labels" . | nindent 4 }}
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        {{- include "xcagi.selectorLabels" . | nindent 8 }}
        app: redis
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: redis
          image: {{ include "xcagi.image" (dict "repository" .Values.redis.image.repository "tag" .Values.redis.image.tag) }}
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.redis.port }}
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
{{- end }}
