{{- if and .Values.api.enabled .Values.secrets.create (not .Values.secrets.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: xcagi-secrets
  namespace: {{ include "xcagi.namespace" . }}
  labels:
    {{- include "xcagi.labels" . | nindent 4 }}
    app: xcagi
type: Opaque
stringData:
  ADMIN_USERNAME: {{ .Values.api.admin.username | quote }}
  ADMIN_PASSWORD: {{ .Values.api.admin.password | quote }}
  {{- range $k, $v := .Values.secrets.extra }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
